<?php
require __DIR__.'/config.php';
$page=$_GET['page']??'home';
$msg='';
if($page==='logout'){session_destroy();header('Location: ./');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 check_csrf();
 $action=$_POST['action']??'';
 try{
  if($action==='register'){
   $email=strtolower(trim($_POST['email']??''));$username=trim($_POST['username']??'');$pw=$_POST['password']??'';
   if(!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($username)<3||strlen($pw)<8)throw new RuntimeException('Enter a valid email, username and password of at least 8 characters.');
   $exists=db()->prepare('SELECT id FROM users WHERE email=? OR username=? LIMIT 1');$exists->execute([$email,$username]);if($exists->fetch())throw new RuntimeException('An account already exists with this email address or username. Please sign in or use Forgot Password.');
   $s=db()->prepare('INSERT INTO users(email,username,password_hash,given_name,family_name,affiliation,country,orcid,reviewing_interests,roles,verified) VALUES(?,?,?,?,?,?,?,?,?,?,1)');
   try{$s->execute([$email,$username,password_hash($pw,PASSWORD_DEFAULT),trim($_POST['given_name']??''),trim($_POST['family_name']??''),trim($_POST['affiliation']??''),trim($_POST['country']??''),trim($_POST['orcid']??''),trim($_POST['reviewing_interests']??''),'Author,Reader']);}catch(PDOException $ex){if(($ex->errorInfo[1]??0)===1062)throw new RuntimeException('An account already exists with this email address or username. Please sign in or use Forgot Password.');throw $ex;}
   $uid=(int)db()->lastInsertId();db()->prepare('UPDATE users SET verified=0 WHERE id=?')->execute([$uid]);$token=bin2hex(random_bytes(32));$hash=hash('sha256',$token);db()->prepare('INSERT INTO email_verifications(user_id,token_hash,expires_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 24 HOUR))')->execute([$uid,$hash]);$url=rtrim(getenv('APP_URL')?:'', '/').'/?page=verify-email&token='.urlencode($token);send_mail($email,'Verify your Nigerian Affairs account','<p>Welcome to Nigerian Affairs.</p><p><a href="'.e($url).'">Verify your email address</a></p><p>This link expires in 24 hours.</p>');
   $msg='Registration successful. Check your email to verify your account before signing in.';$page='login';
  }elseif($action==='login'){
   $id=trim($_POST['identity']??'');$s=db()->prepare('SELECT * FROM users WHERE email=? OR username=? LIMIT 1');$s->execute([strtolower($id),$id]);$x=$s->fetch();
   if(!$x||!password_verify($_POST['password']??'',$x['password_hash']))throw new RuntimeException('Invalid username/email or password.');if(!(int)$x['verified'])throw new RuntimeException('Please verify your email address before signing in.');
   session_regenerate_id(true);$_SESSION['uid']=$x['id'];$adminRoles=array_map('trim',explode(',',$x['roles']??''));$isAdmin=(bool)array_intersect(['Editor','Journal Manager','Site Administrator'],$adminRoles);header('Location: ?page='.($isAdmin?'admin-overview':'dashboard'));exit;
  }elseif($action==='request-reset'){
   $email=strtolower(trim($_POST['email']??''));$q=db()->prepare('SELECT id,email,given_name FROM users WHERE email=? LIMIT 1');$q->execute([$email]);$account=$q->fetch();
   if($account){$token=bin2hex(random_bytes(32));$hash=hash('sha256',$token);db()->prepare('UPDATE password_resets SET used_at=NOW() WHERE user_id=? AND used_at IS NULL')->execute([$account['id']]);db()->prepare('INSERT INTO password_resets(user_id,token_hash,expires_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 15 MINUTE))')->execute([$account['id'],$hash]);$url=rtrim(getenv('APP_URL')?:'', '/').'/?page=reset-password&token='.urlencode($token);send_mail($account['email'],'Nigerian Affairs password reset','<p>Hello '.e($account['given_name']).',</p><p>Use the link below to set a new Nigerian Affairs password. The link expires in 15 minutes.</p><p><a href="'.e($url).'">Reset password</a></p><p>If you did not request this, ignore this email.</p>');}
   $msg='If that email address is registered, a password reset link has been sent.';$page='forgot-password';
  }elseif($action==='confirm-reset'){
   $token=$_POST['token']??'';$pw=$_POST['password']??'';$confirm=$_POST['password_confirm']??'';if(strlen($pw)<8||$pw!==$confirm)throw new RuntimeException('Passwords must match and contain at least 8 characters.');$hash=hash('sha256',$token);$q=db()->prepare('SELECT * FROM password_resets WHERE token_hash=? AND used_at IS NULL AND expires_at>NOW() LIMIT 1');$q->execute([$hash]);$reset=$q->fetch();if(!$reset)throw new RuntimeException('This reset link is invalid or has expired.');db()->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash($pw,PASSWORD_DEFAULT),$reset['user_id']]);db()->prepare('UPDATE password_resets SET used_at=NOW() WHERE id=?')->execute([$reset['id']]);$msg='Password reset successful. You can now log in.';$page='login';
  }elseif($action==='designate-review-file'){
   $editor=require_login();if(!(has_role($editor,'Editor')||has_role($editor,'Journal Manager')||has_role($editor,'Site Administrator')))throw new RuntimeException('Editorial access required.');$fid=(int)($_POST['file_id']??0);$sid=(int)($_POST['submission_id']??0);$q=db()->prepare('SELECT * FROM submission_files WHERE id=? AND submission_id=?');$q->execute([$fid,$sid]);$sf=$q->fetch();if(!$sf)throw new RuntimeException('Submission file not found.');db()->prepare("UPDATE submission_files SET file_role=CASE WHEN file_role='Review File' THEN 'Original Manuscript' ELSE file_role END WHERE submission_id=?")->execute([$sid]);db()->prepare("UPDATE submission_files SET file_role='Review File' WHERE id=?")->execute([$fid]);db()->prepare('INSERT INTO audit_log(user_id,submission_id,action) VALUES(?,?,?)')->execute([$editor['id'],$sid,'Designated review file version '.$sf['version_no']]);header('Location: ?page=editor');exit;
  }elseif($action==='assign-reviewer'){
   $editor=require_login();if(!(has_role($editor,'Editor')||has_role($editor,'Journal Manager')||has_role($editor,'Site Administrator')))throw new RuntimeException('Editorial access required.');
   $sid=(int)($_POST['submission_id']??0);$email=strtolower(trim($_POST['reviewer_email']??''));$days=max(1,min(60,(int)($_POST['review_days']??14)));if(!$sid||!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Enter a valid reviewer email.');
   $q=db()->prepare('SELECT id,given_name,family_name,email FROM users WHERE email=? LIMIT 1');$q->execute([$email]);$reviewer=$q->fetch();if(!$reviewer)throw new RuntimeException('Reviewer must first have a registered Nigerian Affairs account.');
   $q=db()->prepare('SELECT title FROM submissions WHERE id=?');$q->execute([$sid]);$paper=$q->fetch();if(!$paper)throw new RuntimeException('Submission not found.');
   $token=bin2hex(random_bytes(32));$hash=hash('sha256',$token);$s=db()->prepare("INSERT INTO reviews(submission_id,reviewer_id,status,invitation_token_hash,due_at) VALUES(?,?,'Invited',?,DATE_ADD(NOW(),INTERVAL ? DAY))");$s->execute([$sid,$reviewer['id'],$hash,$days]);$rid=(int)db()->lastInsertId();$url=rtrim(getenv('APP_URL')?:'', '/').'/?page=review-invitation&token='.urlencode($token);
   send_mail($reviewer['email'],'Review invitation: '.$paper['title'],'<p>Dear '.e($reviewer['given_name']).',</p><p>You have been invited to review <strong>'.e($paper['title']).'</strong> for Nigerian Affairs.</p><p><a href="'.e($url).'">Respond to review invitation</a></p><p>The requested review period is '.$days.' days.</p>');
   db()->prepare('UPDATE submissions SET stage=?,status=? WHERE id=?')->execute(['Review','Reviewer invited',$sid]);header('Location: ?page=editor');exit;
  }elseif($action==='review-response'){
   $me=require_login();$token=$_POST['token']??'';$response=$_POST['response']??'';$hash=hash('sha256',$token);$q=db()->prepare('SELECT * FROM reviews WHERE invitation_token_hash=? AND reviewer_id=? LIMIT 1');$q->execute([$hash,$me['id']]);$review=$q->fetch();if(!$review||!in_array($response,['Accepted','Declined'],true))throw new RuntimeException('Invalid review invitation.');db()->prepare('UPDATE reviews SET status=?,responded_at=NOW() WHERE id=?')->execute([$response,$review['id']]);$msg='Review invitation '.$response.'.';$page='dashboard';
  }elseif($action==='update-user-role'){
   $admin=require_login();if(!(has_role($admin,'Journal Manager')||has_role($admin,'Site Administrator')))throw new RuntimeException('Administrator access required.');$uid=(int)($_POST['user_id']??0);$roles=$_POST['roles']??[];$allowed=['Reader','Author','Reviewer','Editor','Journal Manager'];$roles=array_values(array_intersect($allowed,(array)$roles));if(!$uid||!$roles)throw new RuntimeException('Select at least one valid role.');db()->prepare('UPDATE users SET roles=? WHERE id=?')->execute([implode(',',$roles),$uid]);db()->prepare('INSERT INTO audit_log(user_id,action) VALUES(?,?)')->execute([$admin['id'],'Updated roles for user '.$uid]);header('Location: ?page=users-roles');exit;
  }elseif($action==='set-user-verification'){
   $admin=require_login();if(!(has_role($admin,'Journal Manager')||has_role($admin,'Site Administrator')))throw new RuntimeException('Administrator access required.');$uid=(int)($_POST['user_id']??0);$verified=(int)($_POST['verified']??0);db()->prepare('UPDATE users SET verified=? WHERE id=?')->execute([$verified?1:0,$uid]);db()->prepare('INSERT INTO audit_log(user_id,action) VALUES(?,?)')->execute([$admin['id'],($verified?'Verified':'Unverified').' user '.$uid]);header('Location: ?page=users-roles');exit;
  }elseif($action==='save-settings'){
   $admin=require_login();if(!(has_role($admin,'Journal Manager')||has_role($admin,'Site Administrator')))throw new RuntimeException('Administrator access required.');foreach(['journal_name','publisher','issn','frequency','contact_email'] as $k){$v=trim($_POST[$k]??'');db()->prepare('INSERT INTO journal_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)')->execute([$k,$v]);}header('Location: ?page=journal-settings');exit;
  }elseif($action==='publish-issue'){
   $admin=require_login();if(!(has_role($admin,'Editor')||has_role($admin,'Journal Manager')||has_role($admin,'Site Administrator')))throw new RuntimeException('Editorial access required.');$iid=(int)($_POST['issue_id']??0);if(!$iid)throw new RuntimeException('Invalid issue.');db()->prepare("UPDATE issues SET status='Published',published_at=COALESCE(published_at,NOW()) WHERE id=?")->execute([$iid]);header('Location: ?page=issue-management');exit;
  }elseif($action==='create-issue'){
   $admin=require_login();if(!(has_role($admin,'Editor')||has_role($admin,'Journal Manager')||has_role($admin,'Site Administrator')))throw new RuntimeException('Editorial access required.');$v=(int)($_POST['volume']??0);$n=(int)($_POST['number']??0);$y=(int)($_POST['year']??0);if($v<1||$n<1||$y<2000)throw new RuntimeException('Enter a valid volume, number and year.');db()->prepare('INSERT INTO issues(volume,number,year,title,description) VALUES(?,?,?,?,?)')->execute([$v,$n,$y,trim($_POST['title']??'')?:null,trim($_POST['description']??'')?:null]);header('Location: ?page=issue-management');exit;
  }elseif($action==='publish-announcement'){
   $admin=require_login();if(!(has_role($admin,'Editor')||has_role($admin,'Journal Manager')||has_role($admin,'Site Administrator')))throw new RuntimeException('Editorial access required.');$title=trim($_POST['title']??'');$body=trim($_POST['body']??'');if($title===''||$body==='')throw new RuntimeException('Announcement title and content are required.');db()->prepare('INSERT INTO announcements(title,body,published_at) VALUES(?,?,NOW())')->execute([$title,$body]);header('Location: ?page=announcement-management');exit;
  }elseif($action==='add-galley'){
   $admin=require_login();if(!(has_role($admin,'Editor')||has_role($admin,'Journal Manager')||has_role($admin,'Site Administrator')))throw new RuntimeException('Editorial access required.');$sid=(int)($_POST['submission_id']??0);$label=trim($_POST['label']??'PDF');if(!$sid||empty($_FILES['galley_pdf']))throw new RuntimeException('Select an article and PDF file.');
   $file=$_FILES['galley_pdf'];if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('PDF upload failed.');if(($file['size']??0)>25*1024*1024)throw new RuntimeException('PDF must not exceed 25 MB.');
   $fh=fopen($file['tmp_name'],'rb');$sig=fread($fh,5);fclose($fh);if($sig!=='%PDF-')throw new RuntimeException('Only genuine PDF files are accepted.');$finfo=new finfo(FILEINFO_MIME_TYPE);$mime=$finfo->file($file['tmp_name']);if(!in_array($mime,['application/pdf','application/x-pdf'],true))throw new RuntimeException('Only PDF files are accepted.');
   $dir=__DIR__.'/storage/uploads';if(!is_dir($dir)&&!mkdir($dir,0770,true))throw new RuntimeException('Upload storage is unavailable.');$name='na-'.$sid.'-'.bin2hex(random_bytes(12)).'.pdf';$dest=$dir.'/'.$name;if(!move_uploaded_file($file['tmp_name'],$dest))throw new RuntimeException('Unable to save PDF.');
   $path='?page=galley&file='.rawurlencode($name);db()->prepare('INSERT INTO galleys(submission_id,label,file_path,mime_type) VALUES(?,?,?,?)')->execute([$sid,$label,$path,'application/pdf']);db()->prepare('INSERT INTO audit_log(user_id,submission_id,action) VALUES(?,?,?)')->execute([$admin['id'],$sid,'PDF galley uploaded']);header('Location: ?page=galley-management');exit;
  }elseif($action==='submit-revision'){
   $me=require_login();$sid=(int)($_POST['submission_id']??0);$response=trim($_POST['response_to_reviewers']??'');if(!$sid||$response==='')throw new RuntimeException('Provide your response to the reviewers.');
   $q=db()->prepare("SELECT * FROM submissions WHERE id=? AND author_id=? AND status='Revision requested'");$q->execute([$sid,$me['id']]);$paper=$q->fetch();if(!$paper)throw new RuntimeException('This manuscript is not awaiting your revision.');if(empty($_FILES['revised_manuscript']))throw new RuntimeException('Upload the revised manuscript.');$file=$_FILES['revised_manuscript'];if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||($file['size']??0)>20*1024*1024)throw new RuntimeException('Revised manuscript upload failed or exceeds 20 MB.');$ext=strtolower(pathinfo($file['name']??'',PATHINFO_EXTENSION));$finfo=new finfo(FILEINFO_MIME_TYPE);$mime=$finfo->file($file['tmp_name']);if(!in_array($ext,['docx','pdf'],true))throw new RuntimeException('Upload a DOCX or PDF revised manuscript.');$vq=db()->prepare('SELECT COALESCE(MAX(version_no),0)+1 FROM submission_files WHERE submission_id=?');$vq->execute([$sid]);$ver=(int)$vq->fetchColumn();$dir=__DIR__.'/storage/manuscripts';if(!is_dir($dir)&&!mkdir($dir,0770,true))throw new RuntimeException('Manuscript storage is unavailable.');$stored='submission-'.$sid.'-v'.$ver.'-'.bin2hex(random_bytes(10)).'.'.$ext;if(!move_uploaded_file($file['tmp_name'],$dir.'/'.$stored))throw new RuntimeException('Unable to save revised manuscript.');db()->prepare('INSERT INTO submission_files(submission_id,uploaded_by,file_stage,file_role,original_name,stored_name,mime_type,file_size,version_no) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$sid,$me['id'],'Revision','Revised Manuscript',basename($file['name']),$stored,$mime,(int)$file['size'],$ver]);db()->prepare('INSERT INTO revisions(submission_id,author_id,response_to_reviewers,revised_title,revised_abstract) VALUES(?,?,?,?,?)')->execute([$sid,$me['id'],$response,trim($_POST['revised_title']??'')?:null,trim($_POST['revised_abstract']??'')?:null]);db()->prepare("UPDATE submissions SET status='Revision submitted',stage='Review' WHERE id=?")->execute([$sid]);db()->prepare('INSERT INTO audit_log(user_id,submission_id,action) VALUES(?,?,?)')->execute([$me['id'],$sid,'Revision submitted']);
   $editorEmail=getenv('EDITOR_EMAIL')?:'';if($editorEmail!=='')send_mail($editorEmail,'Revision submitted: '.$paper['title'],'<p>The author has submitted a revision and response to reviewers for <strong>'.e($paper['title']).'</strong>.</p><p>Please sign in to the editorial workflow.</p>');$msg='Your revision has been submitted.';$page='dashboard';
  }elseif($action==='production-update'){
   $editor=require_login();if(!(has_role($editor,'Editor')||has_role($editor,'Journal Manager')||has_role($editor,'Site Administrator')))throw new RuntimeException('Editorial access required.');$sid=(int)($_POST['submission_id']??0);$step=$_POST['production_step']??'';if(!$sid||!in_array($step,['Copyediting Complete','Move to Production','Publish'],true))throw new RuntimeException('Invalid production action.');$sq=db()->prepare('SELECT stage,status,title,author_id FROM submissions WHERE id=?');$sq->execute([$sid]);$sp=$sq->fetch();if(!$sp)throw new RuntimeException('Submission not found.');
   db()->prepare('INSERT IGNORE INTO production_items(submission_id) VALUES(?)')->execute([$sid]);if($step==='Copyediting Complete'){if($sp['stage']!=='Copyediting')throw new RuntimeException('Only accepted manuscripts in Copyediting can complete copyediting.');db()->prepare("UPDATE production_items SET copyediting_status='Complete' WHERE submission_id=?")->execute([$sid]);db()->prepare("UPDATE submissions SET status='Copyediting complete' WHERE id=?")->execute([$sid]);}elseif($step==='Move to Production'){if($sp['stage']!=='Copyediting'||$sp['status']!=='Copyediting complete')throw new RuntimeException('Complete copyediting before moving to Production.');db()->prepare("UPDATE production_items SET production_status='In production' WHERE submission_id=?")->execute([$sid]);db()->prepare("UPDATE submissions SET stage='Production',status='In production' WHERE id=?")->execute([$sid]);}else{$issueId=(int)($_POST['issue_id']??0);$pages=trim($_POST['pages']??'');if($sp['stage']!=='Production')throw new RuntimeException('Only manuscripts in Production can be published.');$iq=db()->prepare("SELECT * FROM issues WHERE id=? AND status='Published'");$iq->execute([$issueId]);$issue=$iq->fetch();if(!$issue)throw new RuntimeException('Select a published issue before publication.');$gq=db()->prepare("SELECT COUNT(*) FROM galleys WHERE submission_id=? AND mime_type='application/pdf'");$gq->execute([$sid]);if(!(int)$gq->fetchColumn())throw new RuntimeException('Upload a PDF galley before publication.');if(!preg_match('/^\\d+\\s*[-–]\\s*\\d+$/u',$pages))throw new RuntimeException('Enter a page range such as 1-12.');$issueLabel='Vol. '.$issue['volume'].' No. '.$issue['number'].' ('.$issue['year'].')';db()->prepare("UPDATE production_items SET production_status='Published',issue_label=?,pages=?,doi=?,published_at=NOW() WHERE submission_id=?")->execute([$issueLabel,$pages,trim($_POST['doi']??''),$sid]);db()->prepare("UPDATE submissions SET stage='Publication',status='Published' WHERE id=?")->execute([$sid]);$aq=db()->prepare('SELECT email,given_name FROM users WHERE id=?');$aq->execute([$sp['author_id']]);$au=$aq->fetch();if($au)send_mail($au['email'],'Nigerian Affairs article published: '.$sp['title'],'<p>Dear '.e($au['given_name']).',</p><p>Your article <strong>'.e($sp['title']).'</strong> has been published in '.e($issueLabel).'.</p>');}
   db()->prepare('INSERT INTO audit_log(user_id,submission_id,action) VALUES(?,?,?)')->execute([$editor['id'],$sid,$step]);header('Location: ?page=editor');exit;
  }elseif($action==='submit-review'){
   $me=require_login();$rid=(int)($_POST['review_id']??0);$recommendation=trim($_POST['recommendation']??'');$authorComments=trim($_POST['comments_to_author']??'');$editorComments=trim($_POST['comments_to_editor']??'');$allowed=['Accept Submission','Revisions Required','Resubmit for Review','Decline Submission'];if(!$rid||!in_array($recommendation,$allowed,true)||$authorComments==='')throw new RuntimeException('Complete the review and select a recommendation.');
   $q=db()->prepare("SELECT r.*,s.title FROM reviews r JOIN submissions s ON s.id=r.submission_id WHERE r.id=? AND r.reviewer_id=? AND r.status='Accepted' AND r.submitted_at IS NULL");$q->execute([$rid,$me['id']]);$review=$q->fetch();if(!$review)throw new RuntimeException('This review is unavailable or has already been submitted.');
   db()->prepare("UPDATE reviews SET recommendation=?,comments_to_author=?,comments_to_editor=?,status='Submitted',submitted_at=NOW() WHERE id=?")->execute([$recommendation,$authorComments,$editorComments,$rid]);db()->prepare("UPDATE submissions SET status='Review submitted' WHERE id=?")->execute([$review['submission_id']]);db()->prepare('INSERT INTO audit_log(user_id,submission_id,action) VALUES(?,?,?)')->execute([$me['id'],$review['submission_id'],'Peer review submitted']);
   $editorEmail=getenv('EDITOR_EMAIL')?:'';if($editorEmail!=='')send_mail($editorEmail,'Completed review: '.$review['title'],'<p>A reviewer has submitted a completed review for <strong>'.e($review['title']).'</strong>.</p><p>Recommendation: <strong>'.e($recommendation).'</strong></p><p>Sign in to the Nigerian Affairs editorial workflow to read the review.</p>');$msg='Your review has been submitted and locked.';$page='dashboard';
  }elseif($action==='editor-decision'){
   $editor=require_login();if(!(has_role($editor,'Editor')||has_role($editor,'Journal Manager')||has_role($editor,'Site Administrator')))throw new RuntimeException('Editorial access required.');
   $sid=(int)($_POST['submission_id']??0);$decision=trim($_POST['decision']??'');$note=trim($_POST['note']??'');$allowed=['Revisions Required','Accept Submission','Decline Submission'];if(!$sid||!in_array($decision,$allowed,true))throw new RuntimeException('Invalid editorial decision.');
   $q=db()->prepare('SELECT s.title,u.email,u.given_name FROM submissions s JOIN users u ON u.id=s.author_id WHERE s.id=?');$q->execute([$sid]);$paper=$q->fetch();if(!$paper)throw new RuntimeException('Submission not found.');
   db()->prepare('INSERT INTO decisions(submission_id,editor_id,decision,note) VALUES(?,?,?,?)')->execute([$sid,$editor['id'],$decision,$note]);$status=$decision==='Accept Submission'?'Accepted':($decision==='Decline Submission'?'Declined':'Revision requested');$stage=$decision==='Accept Submission'?'Copyediting':($decision==='Decline Submission'?'Review':'Submission');db()->prepare('UPDATE submissions SET status=?,stage=? WHERE id=?')->execute([$status,$stage,$sid]);
   db()->prepare('INSERT INTO audit_log(user_id,submission_id,action) VALUES(?,?,?)')->execute([$editor['id'],$sid,'Editorial decision: '.$decision]);
   send_mail($paper['email'],'Nigerian Affairs editorial decision: '.$paper['title'],'<p>Dear '.e($paper['given_name']).',</p><p>An editorial decision has been recorded for <strong>'.e($paper['title']).'</strong>.</p><p><strong>'.e($decision).'</strong></p><p>'.nl2br(e($note)).'</p><p>Please sign in to your journal dashboard for the manuscript record.</p>');
   header('Location: ?page=editor');exit;
  }elseif($action==='submit'){
   $me=require_login();if(empty($_FILES['manuscript']))throw new RuntimeException('Upload your manuscript file.');$file=$_FILES['manuscript'];if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('Manuscript upload failed.');if(($file['size']??0)>20*1024*1024)throw new RuntimeException('Manuscript must not exceed 20 MB.');$ext=strtolower(pathinfo($file['name']??'',PATHINFO_EXTENSION));$finfo=new finfo(FILEINFO_MIME_TYPE);$mime=$finfo->file($file['tmp_name']);$allowed=['docx'=>'application/vnd.openxmlformats-officedocument.wordprocessingml.document','pdf'=>'application/pdf'];if(!isset($allowed[$ext])||($mime!==$allowed[$ext]&& !($ext==='docx'&&in_array($mime,['application/zip','application/octet-stream'],true))))throw new RuntimeException('Upload a DOCX or PDF manuscript.');
   $s=db()->prepare('INSERT INTO submissions(author_id,title,authors,abstract,keywords,section,language,references_text) VALUES(?,?,?,?,?,?,?,?)');$title=trim($_POST['title']??'');$s->execute([$me['id'],$title,trim($_POST['authors']??''),trim($_POST['abstract']??''),trim($_POST['keywords']??''),$_POST['section']??'Research Article',$_POST['language']??'English',trim($_POST['references']??'')]);$sid=(int)db()->lastInsertId();$dir=__DIR__.'/storage/manuscripts';if(!is_dir($dir)&&!mkdir($dir,0770,true))throw new RuntimeException('Manuscript storage is unavailable.');$stored='submission-'.$sid.'-v1-'.bin2hex(random_bytes(10)).'.'.$ext;if(!move_uploaded_file($file['tmp_name'],$dir.'/'.$stored))throw new RuntimeException('Unable to save manuscript.');db()->prepare('INSERT INTO submission_files(submission_id,uploaded_by,file_stage,file_role,original_name,stored_name,mime_type,file_size,version_no) VALUES(?,?,?,?,?,?,?,?,1)')->execute([$sid,$me['id'],'Submission','Original Manuscript',basename($file['name']),$stored,$mime,(int)$file['size']]);db()->prepare('INSERT INTO audit_log(user_id,submission_id,action) VALUES(?,?,?)')->execute([$me['id'],$sid,'Submission received with manuscript file']);
   send_mail($me['email'],'Nigerian Affairs submission received','<p>Dear '.e($me['given_name']).',</p><p>Your manuscript <strong>'.e($title).'</strong> has been received by Nigerian Affairs.</p><p>Submission ID: NA-'.str_pad((string)$sid,6,'0',STR_PAD_LEFT).'</p><p>You can monitor its status from your journal dashboard.</p>');
   $editor=getenv('EDITOR_EMAIL')?:'';if($editor!=='')send_mail($editor,'New Nigerian Affairs submission: '.$title,'<p>A new manuscript has been submitted to Nigerian Affairs.</p><p><strong>'.e($title).'</strong></p><p>Submission ID: NA-'.str_pad((string)$sid,6,'0',STR_PAD_LEFT).'</p><p>Please sign in to the editorial dashboard for screening.</p>');
   header('Location: ?page=dashboard');exit;
  }
 }catch(Throwable $ex){$msg=$ex->getMessage();}
}
if($page==='verify-email'&&!empty($_GET['token'])){$hash=hash('sha256',$_GET['token']);$q=db()->prepare('SELECT * FROM email_verifications WHERE token_hash=? AND used_at IS NULL AND expires_at>NOW() LIMIT 1');$q->execute([$hash]);$v=$q->fetch();if($v){db()->prepare('UPDATE users SET verified=1 WHERE id=?')->execute([$v['user_id']]);db()->prepare('UPDATE email_verifications SET used_at=NOW() WHERE id=?')->execute([$v['id']]);$msg='Email verified successfully. You can now log in.';$page='login';}else{$msg='This verification link is invalid or has expired.';}}
$u=current_user();
if($page==='dashboard'&&$u&&(has_role($u,'Editor')||has_role($u,'Journal Manager')||has_role($u,'Site Administrator'))){header('Location: ?page=admin-overview');exit;}
$adminChromePages=['admin-overview','editor','editor-submissions','editor-workflow','users-roles','journal-settings','audit-report','issue-management','announcement-management','galley-management'];
$adminChrome=in_array($page,$adminChromePages,true);
$protectedPages=['dashboard','admin-overview','editor','editor-submissions','editor-workflow','submissions','submission-file','revision','review','review-invitation','users-roles','journal-settings','audit-report','issue-management','announcement-management','galley-management'];
if(in_array($page,$protectedPages,true)&&!$u){header('Location: ?page=login');exit;}
?><!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e(ucfirst($page))?> | Nigerian Affairs</title><link rel="stylesheet" href="assets/style.css"></head><body>
<?php if(!$adminChrome): ?>
<div class="utility"><div class="wide"><span>English</span><span><?php if($u): ?><a href="?page=dashboard">Dashboard</a><?php if(has_role($u,'Journal Manager')||has_role($u,'Site Administrator')): ?> · <a href="?page=admin-overview">Administration</a><?php endif; ?> · <a href="?page=logout">Logout</a><?php else: ?><a href="?page=register">Register</a> · <a href="?page=login">Login</a><?php endif; ?></span></div></div>
<header><div class="wide brand"><img src="assets/na-logo.svg" alt="Nigerian Affairs NA logo" style="width:82px;height:64px;object-fit:contain"><div><h1>Nigerian Affairs</h1><small>ARTS · HUMANITIES · SOCIAL SCIENCES</small></div></div><nav class="wide"><a href="./">Home</a><a href="?page=about">About the journal</a><a href="?page=current">Current</a><a href="?page=policies">Journal Policies</a><a href="?page=editorial">Editorial Team</a><a href="?page=submissions">Instructions to Authors</a><a href="?page=archives">Archives</a><a href="?page=search">Search</a><a href="?page=announcements">Announcements</a><a href="?page=contact">Contact</a></nav></header>
<?php endif; ?>
<?php if($msg): ?><div class="wide alert"><?=e($msg)?><?php if(str_contains($msg,'already exists')): ?><br><a href="?page=login">Sign in</a> · <a href="?page=forgot-password">Forgot Password</a><?php endif; ?></div><?php endif; ?>
<?php if($page==='login'): ?>
<style>
.na-login-wrap{font-family:"Noto Sans",-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;font-size:14px;line-height:20px;display:grid;grid-template-columns:minmax(0,1fr) 300px;width:1160px;max-width:calc(100% - 40px);margin:0 auto;border-left:1px solid #ddd;border-right:1px solid #ddd;min-height:720px;color:rgba(0,0,0,.87)}
.na-login-main{padding:30px 40px}.na-breadcrumb{margin:0 0 40px;color:#006798;font-size:14px}.na-breadcrumb a{color:#006798;text-decoration:none}.na-login-main h2{font-family:inherit;font-size:24px;line-height:30px;font-weight:700;margin:0 0 20px}.na-required{font-size:14px;line-height:25px;margin:0 0 20px}
.na-login-form{width:330px;max-width:100%}.na-login-form label{font-family:inherit;font-size:14px;line-height:20px;font-weight:700;margin:20px 0 5px}.na-login-form .star{display:block;font-weight:700;line-height:20px;margin-bottom:5px}.na-login-form input[type=text],.na-login-form input[type=password]{box-sizing:border-box;width:330px;max-width:100%;height:40px;padding:10px;border:1px solid rgba(0,0,0,.4);border-radius:3px;background:#eef4fc;font:14px/20px inherit}.na-login-form .forgot{display:block;color:#006798;text-decoration:none;margin:10px 0 40px}.na-remember{display:flex!important;align-items:center;gap:8px;font-weight:400!important;margin:0 0 60px!important}.na-remember input{width:auto!important;margin:0}.na-login-actions{display:flex;justify-content:flex-end;align-items:center;gap:20px}.na-login-actions a{color:#006798;text-decoration:none}.na-login-actions button{font:700 14px/20px inherit;padding:10px 15px;border:0;border-radius:3px;background:#eee;color:#006798;margin:0}
.na-login-side{border-left:1px solid #ddd;padding:30px;font-size:14px;line-height:20px}.na-login-side h3{font-family:inherit;font-size:16px;line-height:20px;font-weight:700;color:rgba(0,0,0,.54);margin:0 0 10px}.na-login-side a{display:block;color:#006798;text-decoration:none;padding:5px 0;margin:0}.na-journal-card{border:1px solid #ddd;padding:10px;margin-top:40px;width:180px}.na-journal-card b{font-size:12px;line-height:15px}.na-journal-card small{display:block;text-align:right;color:rgba(0,0,0,.54);margin-top:10px;font-size:12px}.na-oa{width:45px;height:45px;border-radius:50%;background:#d5cf20;color:#fff;display:grid;place-items:center;font-weight:700;font-size:18px;margin:8px 0}.na-share{border-top:1px solid #ddd;margin-top:30px;padding-top:20px}.na-share span{display:block;padding:7px 10px;background:#168bc0;color:#fff;margin:8px 0;font-size:12px;line-height:16px}
@media(max-width:992px){.na-login-wrap{width:calc(100% - 40px);grid-template-columns:minmax(0,1fr) 260px}}@media(max-width:768px){.na-login-wrap{display:block;max-width:100%;width:100%;border:0}.na-login-main{padding:20px}.na-login-side{border-left:0;border-top:1px solid #ddd;padding:20px}}
</style>
<div class="na-login-wrap"><main class="na-login-main"><div class="na-breadcrumb"><a href="./">Home</a> &nbsp;/&nbsp; Login</div><h2>Login</h2><div class="na-required">Required fields are marked with an asterisk: *</div><form method="post" class="na-login-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="login"><label>Email or username</label><span class="star">*</span><input type="text" name="identity" required autofocus><label>Password</label><span class="star">*</span><input type="password" name="password" required><a class="forgot" href="?page=forgot-password">Forgot your password?</a><label class="na-remember"><input type="checkbox" name="remember" value="1"> Keep me logged in</label><div class="na-login-actions"><a href="?page=register">Register</a><button>Login</button></div></form></main><aside class="na-login-side"><h3>Information</h3><a href="?page=about">For Readers</a><a href="?page=submissions">For Authors</a><a href="?page=about">For Librarians</a><div class="na-journal-card"><b>Nigerian Affairs</b><small>Arts · Humanities · Social Sciences</small><div class="na-oa">OA</div><span>Peer-reviewed · Open access</span></div><div class="na-share"><span>𝕏 &nbsp; tweet</span><span>f &nbsp; share</span><span>in &nbsp; share</span><span>p &nbsp; pin it</span><span>WhatsApp &nbsp; share</span><span>✉ &nbsp; mail</span></div></aside></div>
<?php elseif($page==='forgot-password'): ?>
<main class="wide content narrow"><h2>Reset Password</h2><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="request-reset"><label>Email Address</label><input type="email" name="email" required autofocus><button>Send Reset Link</button></form><p><a href="?page=login">Back to login</a></p></main>
<?php elseif($page==='reset-password'): ?>
<main class="wide content narrow"><h2>Set New Password</h2><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="confirm-reset"><input type="hidden" name="token" value="<?=e($_GET['token']??'')?>"><label>New Password</label><input type="password" name="password" minlength="8" required><label>Confirm New Password</label><input type="password" name="password_confirm" minlength="8" required><button>Set New Password</button></form></main>
<?php elseif($page==='register'): ?>
<main class="wide content narrow"><h2>Register</h2><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="register"><label>Given Name</label><input name="given_name" required><label>Family Name</label><input name="family_name" required><label>Affiliation</label><input name="affiliation"><label>Country</label><input name="country"><label>Email</label><input type="email" name="email" required><label>Username</label><input name="username" required><label>Password</label><input type="password" name="password" minlength="8" required><label>ORCID iD</label><input name="orcid"><label>Reviewing interests</label><textarea name="reviewing_interests"></textarea><button>Register</button></form></main>
<?php elseif($page==='dashboard'): $me=require_login();$q=db()->prepare('SELECT * FROM submissions WHERE author_id=? ORDER BY created_at DESC');$q->execute([$me['id']]);$subs=$q->fetchAll(); ?>
<main class="wide content"><h2>Dashboard</h2><p><?=e($me['given_name'].' '.$me['family_name'])?> · <?=e($me['roles'])?></p><nav class="admin-nav"><a class="button" href="?page=submissions">New Submission</a><?php if(has_role($me,'Editor')||has_role($me,'Journal Manager')||has_role($me,'Site Administrator')): ?><a class="button" href="?page=editor">Editorial Workflow</a><a class="button" href="?page=admin-overview">Administration</a><a class="button" href="?page=issue-management">Issues</a><a class="button" href="?page=announcement-management">Announcements</a><a class="button" href="?page=galley-management">Galleys</a><?php endif; ?><?php if(has_role($me,'Journal Manager')||has_role($me,'Site Administrator')): ?><a class="button" href="?page=users-roles">Users & Roles</a><a class="button" href="?page=journal-settings">Journal Settings</a><a class="button" href="?page=audit-report">Reports & Audit</a><?php endif; ?></nav><h3>My Reviews</h3><?php $rq=db()->prepare("SELECT r.*,s.title FROM reviews r JOIN submissions s ON s.id=r.submission_id WHERE r.reviewer_id=? ORDER BY r.created_at DESC");$rq->execute([$me['id']]);$myReviews=$rq->fetchAll();if(!$myReviews): ?><p>No review assignments.</p><?php endif; ?><?php foreach($myReviews as $rv): ?><div class="paper"><b><?=e($rv['title'])?></b><br><?=e($rv['status'])?><?php if($rv['status']==='Accepted'&&!$rv['submitted_at']): ?> · <a href="?page=review&id=<?=(int)$rv['id']?>">Complete Review</a><?php endif; ?></div><?php endforeach; ?><h3>My Submissions</h3><?php if(!$subs): ?><p>No submissions.</p><?php endif; ?><?php foreach($subs as $s): ?><div class="paper"><b><?=e($s['title'])?></b><br><?=e($s['stage'])?> · <?=e($s['status'])?><?php if($s['status']==='Revision requested'): ?> · <a href="?page=revision&id=<?=(int)$s['id']?>">Submit Revision</a><?php endif; ?></div><?php endforeach; ?></main>
<?php elseif($page==='editor-submissions'): $editor=require_login();if(!(has_role($editor,'Editor')||has_role($editor,'Journal Manager')||has_role($editor,'Site Administrator'))){http_response_code(403);exit('Access denied');}$queue=$_GET['queue']??'my';$where=$queue==='archives'?"s.status IN ('Published','Declined')":($queue==='unassigned'?"NOT EXISTS (SELECT 1 FROM reviews r WHERE r.submission_id=s.id) AND s.status NOT IN ('Published','Declined')":"s.status NOT IN ('Published','Declined')");$q=db()->query("SELECT s.*,u.given_name,u.family_name,(SELECT COUNT(*) FROM reviews r WHERE r.submission_id=s.id) review_count FROM submissions s JOIN users u ON u.id=s.author_id WHERE $where ORDER BY s.updated_at DESC");$queueItems=$q->fetchAll(); ?>
<style>
.ojs35{--nav:#263746;--nav2:#1f2d38;--blue:#006798;--line:#d5dadd;--bg:#f5f6f7;display:flex;min-height:100vh;background:var(--bg);font-family:Arial,Helvetica,sans-serif;color:#333}.ojs35 *{box-sizing:border-box}.ojs35-side{width:230px;background:var(--nav);color:#fff;flex:0 0 230px}.ojs35-logo{padding:22px 20px;border-bottom:1px solid #40515f;font-size:20px;font-weight:700}.ojs35-logo small{display:block;font-size:11px;color:#b9c5ce;margin-top:5px;font-weight:400}.ojs35-menu a{display:block;color:#dce5eb;text-decoration:none;padding:13px 20px;border-left:4px solid transparent}.ojs35-menu a:hover,.ojs35-menu a.on{background:var(--nav2);border-left-color:#4aa3d2;color:#fff}.ojs35-menu .sep{border-top:1px solid #40515f;margin:10px 0}.ojs35-main{flex:1;min-width:0}.ojs35-bar{height:64px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 28px}.ojs35-bar b{color:#4b5964}.ojs35-content{padding:28px;max-width:1400px}.ojs35 h1{font-size:28px;font-weight:400;margin:0 0 22px;color:#333}.ojs35-tabs{background:#fff;border:1px solid var(--line);border-bottom:0}.ojs35-tabs a{display:inline-block;padding:14px 20px;text-decoration:none;color:#536675;border-bottom:3px solid transparent}.ojs35-tabs a.on{color:var(--blue);border-bottom-color:var(--blue);font-weight:700}.ojs35-panel{background:#fff;border:1px solid var(--line);padding:20px;margin-bottom:18px}.ojs35-tools{display:flex;gap:10px;margin-bottom:16px}.ojs35-tools input,.ojs35-tools select{padding:9px;border:1px solid #bfc7cd}.ojs35 table{width:100%;border-collapse:collapse;background:#fff}.ojs35 th{font-size:12px;text-transform:uppercase;color:#647581;background:#f0f2f3;padding:12px;text-align:left;border-bottom:1px solid var(--line)}.ojs35 td{padding:14px 12px;border-bottom:1px solid #e2e6e8;vertical-align:top}.ojs35 .stage{font-size:12px;color:#687b89}.ojs35 .button,.ojs35 button{background:#0073aa;color:#fff;border:0;border-radius:3px;padding:9px 14px;text-decoration:none;cursor:pointer}.ojs35 label{display:block;margin-top:12px;font-weight:700}.ojs35 input,.ojs35 select,.ojs35 textarea{max-width:100%;padding:9px;border:1px solid #bbc4ca}.ojs35 textarea{width:100%;min-height:100px}.ojs35-grid{display:grid;grid-template-columns:minmax(0,1fr) 290px;gap:18px}.ojs35-card{background:#fff;border:1px solid var(--line);padding:18px}.ojs35-card h3{margin-top:0;font-size:17px}.ojs35-steps{display:flex;border-bottom:1px solid var(--line);background:#fff;margin-bottom:18px}.ojs35-steps a{flex:1;text-align:center;padding:14px;text-decoration:none;color:#566975;border-bottom:4px solid transparent}.ojs35-steps a.on{color:#006798;border-bottom-color:#006798;font-weight:700}@media(max-width:850px){.ojs35-side{width:190px;flex-basis:190px}.ojs35-grid{grid-template-columns:1fr}}
</style>
<div class="ojs35"><aside class="ojs35-side"><h2>Nigerian Affairs</h2><a href="?page=admin-overview">Dashboard</a><a class="on" href="?page=editor-submissions&queue=my">Submissions</a><a href="?page=issue-management">Issues</a><a href="?page=users-roles">Users & Roles</a><a href="?page=journal-settings">Settings</a><a href="?page=audit-report">Tools</a><a href="./">View Site</a><a href="?page=logout">Log Out</a></aside><section class="ojs35-main"><div class="ojs35-bar"><h2>Submissions</h2></div><div class="ojs35-content"><div class="ojs35-tabs"><a class="<?=$queue==='my'?'on':''?>" href="?page=editor-submissions&queue=my">My Queue</a><a class="<?=$queue==='unassigned'?'on':''?>" href="?page=editor-submissions&queue=unassigned">Unassigned</a><a class="<?=$queue==='active'?'on':''?>" href="?page=editor-submissions&queue=active">All Active</a><a class="<?=$queue==='archives'?'on':''?>" href="?page=editor-submissions&queue=archives">Archives</a></div><table class="ojs35-table"><thead><tr><th>ID</th><th>Title / Author</th><th>Stage</th><th>Status</th><th>Reviews</th><th></th></tr></thead><tbody><?php if(!$queueItems): ?><tr><td colspan="6">No submissions in this queue.</td></tr><?php endif; ?><?php foreach($queueItems as $s): ?><tr><td>NA-<?=(int)$s['id']?></td><td><strong><?=e($s['title'])?></strong><br><small><?=e($s['given_name'].' '.$s['family_name'])?></small></td><td><?=e($s['stage'])?></td><td><?=e($s['status'])?></td><td><?=(int)$s['review_count']?></td><td><a class="button" href="?page=editor-workflow&id=<?=(int)$s['id']?>">View</a></td></tr><?php endforeach; ?></tbody></table></div></section></div>
<?php elseif($page==='editor-workflow'): $editor=require_login();if(!(has_role($editor,'Editor')||has_role($editor,'Journal Manager')||has_role($editor,'Site Administrator'))){http_response_code(403);exit('Access denied');}$sid=(int)($_GET['id']??0);$q=db()->prepare('SELECT s.*,u.given_name,u.family_name,u.email FROM submissions s JOIN users u ON u.id=s.author_id WHERE s.id=?');$q->execute([$sid]);$paper=$q->fetch();if(!$paper){http_response_code(404);exit('Submission not found');}$tab=$_GET['tab']??strtolower($paper['stage']);if(!in_array($tab,['submission','review','copyediting','production'],true))$tab='submission'; ?>
<div class="ojs35"><aside class="ojs35-side"><h2>Nigerian Affairs</h2><a href="?page=admin-overview">Dashboard</a><a class="on" href="?page=editor-submissions&queue=active">Submissions</a><a href="?page=issue-management">Issues</a><a href="?page=users-roles">Users & Roles</a><a href="?page=journal-settings">Settings</a><a href="?page=audit-report">Tools</a><a href="./">View Site</a><a href="?page=logout">Log Out</a></aside><section class="ojs35-main"><div class="ojs35-bar"><small>NA-<?=(int)$paper['id']?></small><h2><?=e($paper['title'])?></h2><div><?=e($paper['given_name'].' '.$paper['family_name'])?></div></div><div class="ojs35-content"><div class="ojs35-tabs"><?php foreach(['submission','review','copyediting','production'] as $t): ?><a class="<?=$tab===$t?'on':''?>" href="?page=editor-workflow&id=<?=$sid?>&tab=<?=$t?>"><?=e(ucfirst($t))?></a><?php endforeach; ?></div>
<?php if($tab==='submission'): ?><div class="paper"><h3>Submission Files</h3><?php $fq=db()->prepare('SELECT * FROM submission_files WHERE submission_id=? ORDER BY version_no DESC');$fq->execute([$sid]);foreach($fq->fetchAll() as $sf): ?><p><a href="?page=submission-file&id=<?=(int)$sf['id']?>"><?=e($sf['original_name'])?></a> · <?=e($sf['file_role'])?> v<?=(int)$sf['version_no']?><?php if($sf['file_role']!=='Review File'): ?> <form method="post" style="display:inline"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="designate-review-file"><input type="hidden" name="submission_id" value="<?=$sid?>"><input type="hidden" name="file_id" value="<?=(int)$sf['id']?>"><button>Use as Review File</button></form><?php endif; ?></p><?php endforeach; ?></div>
<?php elseif($tab==='review'): ?><div class="paper"><h3>Reviewers</h3><?php $rr=db()->prepare("SELECT r.*,u.given_name,u.family_name,u.email FROM reviews r JOIN users u ON u.id=r.reviewer_id WHERE r.submission_id=? ORDER BY r.created_at");$rr->execute([$sid]);foreach($rr->fetchAll() as $rev): ?><p><strong><?=e($rev['given_name'].' '.$rev['family_name'])?></strong> · <?=e($rev['status'])?><?=!empty($rev['recommendation'])?' · '.e($rev['recommendation']):''?></p><?php endforeach; ?><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="assign-reviewer"><input type="hidden" name="submission_id" value="<?=$sid?>"><label>Reviewer Email</label><input type="email" name="reviewer_email" required><label>Review Period (days)</label><input type="number" name="review_days" value="14" min="1" max="60"><button>Assign Reviewer</button></form><hr><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="editor-decision"><input type="hidden" name="submission_id" value="<?=$sid?>"><label>Editorial Decision</label><select name="decision" required><option></option><option>Revisions Required</option><option>Accept Submission</option><option>Decline Submission</option></select><label>Decision Note</label><textarea name="note"></textarea><button>Record Decision</button></form></div>
<?php elseif($tab==='copyediting'): ?><div class="paper"><h3>Copyediting</h3><p>Status: <?=e($paper['stage']==='Copyediting'?$paper['status']:'Not yet in copyediting')?></p><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="production-update"><input type="hidden" name="submission_id" value="<?=$sid?>"><input type="hidden" name="production_step" value="Copyediting Complete"><button>Complete Copyediting</button></form></div>
<?php else: ?><div class="paper"><h3>Production</h3><p>Current status: <?=e($paper['status'])?></p><p><a href="?page=galley-management">Manage publication galleys</a> · <a href="?page=issue-management">Manage issues</a></p><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="production-update"><input type="hidden" name="submission_id" value="<?=$sid?>"><label>Production Action</label><select name="production_step"><option>Move to Production</option><option>Publish</option></select><label>Published Issue</label><select name="issue_id"><option value="">Select issue</option><?php $iq=db()->query("SELECT * FROM issues WHERE status='Published' ORDER BY year DESC,volume DESC,number DESC");foreach($iq->fetchAll() as $iss): ?><option value="<?=(int)$iss['id']?>">Vol. <?=(int)$iss['volume']?> No. <?=(int)$iss['number']?> (<?=(int)$iss['year']?>)</option><?php endforeach; ?></select><label>Pages</label><input name="pages" placeholder="1-12"><label>DOI</label><input name="doi"><button>Update Production</button></form></div><?php endif; ?></div></section></div>
<?php elseif($page==='editor'): $editor=require_login(); if(!(has_role($editor,'Editor')||has_role($editor,'Journal Manager')||has_role($editor,'Site Administrator'))){http_response_code(403); ?>
<main class="wide content"><h2>Access denied</h2></main>
<?php }else{$items=db()->query('SELECT s.*,u.given_name,u.family_name FROM submissions s JOIN users u ON u.id=s.author_id ORDER BY s.created_at DESC')->fetchAll(); ?>
<main class="wide content"><h2>Editorial Workflow</h2><p>Submission · Review · Copyediting · Production</p><?php if(!$items): ?><p>No submissions awaiting editorial work.</p><?php endif; ?><?php foreach($items as $paper): ?><div class="paper"><h3><?=e($paper['title'])?></h3><p>Author: <?=e($paper['given_name'].' '.$paper['family_name'])?><br>Stage: <?=e($paper['stage'])?> · Status: <?=e($paper['status'])?></p><?php $fq=db()->prepare('SELECT * FROM submission_files WHERE submission_id=? ORDER BY version_no DESC');$fq->execute([$paper['id']]);$files=$fq->fetchAll();if($files): ?><div><strong>Submission Files</strong><?php foreach($files as $sf): ?><div><a href="?page=submission-file&id=<?=(int)$sf['id']?>"><?=e($sf['file_role'])?> v<?=(int)$sf['version_no']?> — <?=e($sf['original_name'])?></a><?php if($sf['file_role']!=='Review File'): ?><form method="post" style="display:inline"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="designate-review-file"><input type="hidden" name="submission_id" value="<?=(int)$paper['id']?>"><input type="hidden" name="file_id" value="<?=(int)$sf['id']?>"><button>Use as Review File</button></form><?php else: ?> <strong>✓ Reviewer file</strong><?php endif; ?></div><?php endforeach; ?></div><?php endif; ?>
<?php $rr=db()->prepare("SELECT r.*,u.given_name,u.family_name,u.email FROM reviews r LEFT JOIN users u ON u.id=r.reviewer_id WHERE r.submission_id=? ORDER BY r.created_at");$rr->execute([$paper['id']]);$assigned=$rr->fetchAll(); ?>
<?php if($assigned): ?><h4>Peer Reviews</h4><?php foreach($assigned as $rev): ?><div class="paper"><strong><?=e(trim(($rev['given_name']??'').' '.($rev['family_name']??'')))?></strong><br>Status: <?=e($rev['status'])?><?php if($rev['due_at']): ?> · Due: <?=e($rev['due_at'])?><?php endif; ?><?php if($rev['submitted_at']): ?><br><strong>Recommendation:</strong> <?=e($rev['recommendation']??'')?><h4>Comments to Author</h4><p><?=nl2br(e($rev['comments_to_author']??''))?></p><h4>Confidential Comments to Editor</h4><p><?=nl2br(e($rev['comments_to_editor']??''))?></p><small>Submitted: <?=e($rev['submitted_at'])?></small><?php endif; ?></div><?php endforeach; ?><?php endif; ?>
<form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="production-update"><input type="hidden" name="submission_id" value="<?=(int)$paper['id']?>"><label>Post-Review Workflow</label><select name="production_step" required><option value="">Select action</option><option>Copyediting Complete</option><option>Move to Production</option><option>Publish</option></select><label>Published Issue</label><select name="issue_id"><option value="">Select issue</option><?php $iq=db()->query("SELECT * FROM issues WHERE status='Published' ORDER BY year DESC,volume DESC,number DESC");foreach($iq->fetchAll() as $iss): ?><option value="<?=(int)$iss['id']?>">Vol. <?=(int)$iss['volume']?> No. <?=(int)$iss['number']?> (<?=(int)$iss['year']?>)<?=!empty($iss['title'])?' — '.e($iss['title']):''?></option><?php endforeach; ?></select><label>Pages</label><input name="pages" placeholder="1-12"><label>DOI</label><input name="doi"><button>Update Workflow</button></form><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="assign-reviewer"><input type="hidden" name="submission_id" value="<?=(int)$paper['id']?>"><label>Reviewer Email</label><input type="email" name="reviewer_email" required><label>Review Period (days)</label><input type="number" name="review_days" value="14" min="1" max="60"><button>Assign Reviewer & Send Invitation</button></form><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="editor-decision"><input type="hidden" name="submission_id" value="<?=(int)$paper['id']?>"><label>Editorial Decision</label><select name="decision" required><option value="">Select decision</option><option>Revisions Required</option><option>Accept Submission</option><option>Decline Submission</option></select><label>Decision Note</label><textarea name="note"></textarea><button>Record Decision & Notify Author</button></form></div><?php endforeach; ?></main>
<?php } ?>
<?php elseif($page==='submissions'): require_login(); ?>
<main class="wide content"><h2>New Submission</h2><div class="steps">1. Start　2. Upload Submission　3. Enter Metadata　4. Confirmation　5. Next Steps</div><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="submit"><label>Manuscript File (DOCX or PDF)</label><input type="file" name="manuscript" accept=".docx,.pdf,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" required><small>Maximum 20 MB. For double-blind review, remove author-identifying information from the review manuscript.</small><label>Manuscript title</label><input name="title" required><label>Authors</label><input name="authors" required><label>Abstract</label><textarea name="abstract" required></textarea><label>Keywords</label><input name="keywords" required><label>Section</label><select name="section"><option>Research Article</option><option>Review Article</option><option>Commentary</option></select><label>Language</label><select name="language"><option>English</option></select><label>References</label><textarea name="references"></textarea><button>Save and Continue</button></form></main>
<?php elseif($page==='submission-file'): $me=require_login();$fid=(int)($_GET['id']??0);$q=db()->prepare('SELECT sf.*,s.author_id FROM submission_files sf JOIN submissions s ON s.id=sf.submission_id WHERE sf.id=?');$q->execute([$fid]);$sf=$q->fetch();if(!$sf){http_response_code(404);exit('Not Found');}$editor=has_role($me,'Editor')||has_role($me,'Journal Manager')||has_role($me,'Site Administrator');$reviewer=false;if(has_role($me,'Reviewer')){$rq=db()->prepare("SELECT COUNT(*) FROM reviews WHERE submission_id=? AND reviewer_id=? AND status IN ('Accepted','Submitted')");$rq->execute([$sf['submission_id'],$me['id']]);$reviewer=(bool)$rq->fetchColumn();}if($reviewer&&$sf['file_role']!=='Review File'){$reviewer=false;}if((int)$sf['author_id']!==(int)$me['id']&&!$editor&&!$reviewer){http_response_code(403);exit('Access denied');}$full=__DIR__.'/storage/manuscripts/'.basename($sf['stored_name']);if(!is_file($full)){http_response_code(404);exit('File not found');}header('Content-Type: '.$sf['mime_type']);header('Content-Length: '.filesize($full));header('Content-Disposition: attachment; filename="'.preg_replace('/[^A-Za-z0-9._-]/','_',basename($sf['original_name'])).'"');readfile($full);exit; ?>
<?php elseif($page==='revision'): $me=require_login();$sid=(int)($_GET['id']??0);$q=db()->prepare("SELECT * FROM submissions WHERE id=? AND author_id=? AND status='Revision requested'");$q->execute([$sid,$me['id']]);$rp=$q->fetch(); ?>
<main class="wide content"><h2>Submit Revision</h2><?php if(!$rp): ?><p>This manuscript is not awaiting a revision.</p><?php else: ?><h3><?=e($rp['title'])?></h3><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="submit-revision"><input type="hidden" name="submission_id" value="<?=(int)$rp['id']?>"><label>Revised Manuscript (DOCX or PDF)</label><input type="file" name="revised_manuscript" accept=".docx,.pdf" required><label>Response to Reviewers</label><textarea name="response_to_reviewers" required></textarea><label>Revised Title (if changed)</label><input name="revised_title"><label>Revised Abstract (if changed)</label><textarea name="revised_abstract"></textarea><button>Submit Revision</button></form><?php endif; ?></main>
<?php elseif($page==='review'): $me=require_login();$rid=(int)($_GET['id']??0);$q=db()->prepare("SELECT r.*,s.title,s.abstract,s.keywords,s.section FROM reviews r JOIN submissions s ON s.id=r.submission_id WHERE r.id=? AND r.reviewer_id=? LIMIT 1");$q->execute([$rid,$me['id']]);$rv=$q->fetch(); ?>
<main class="wide content"><h2>Peer Review</h2><?php if(!$rv): ?><p>Review assignment not found.</p><?php elseif($rv['status']!=='Accepted'&&$rv['status']!=='Submitted'): ?><p>You must accept the review invitation before accessing the review form.</p><?php else: ?><h3><?=e($rv['title'])?></h3><p><strong>Section:</strong> <?=e($rv['section'])?></p><h3>Abstract</h3><p><?=nl2br(e($rv['abstract']))?></p><p><strong>Keywords:</strong> <?=e($rv['keywords'])?></p><?php $fq=db()->prepare("SELECT * FROM submission_files WHERE submission_id=? AND file_role='Review File' ORDER BY version_no DESC LIMIT 1");$fq->execute([$rv['submission_id']]);$rf=$fq->fetch();if($rf): ?><p><a class="button" href="?page=submission-file&id=<?=(int)$rf['id']?>">Download Review Manuscript</a></p><?php else: ?><p class="alert">The editor has not yet released an anonymised review file.</p><?php endif; ?><?php if($rv['submitted_at']): ?><div class="alert">This review was submitted and is locked.</div><h3>Recommendation</h3><p><?=e($rv['recommendation'])?></p><h3>Comments to Author</h3><p><?=nl2br(e($rv['comments_to_author']))?></p><h3>Confidential Comments to Editor</h3><p><?=nl2br(e($rv['comments_to_editor']))?></p><?php else: ?><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="submit-review"><input type="hidden" name="review_id" value="<?=(int)$rv['id']?>"><label>Comments to Author</label><textarea name="comments_to_author" required></textarea><label>Confidential Comments to Editor</label><textarea name="comments_to_editor"></textarea><label>Recommendation</label><select name="recommendation" required><option value="">Select recommendation</option><option>Accept Submission</option><option>Revisions Required</option><option>Resubmit for Review</option><option>Decline Submission</option></select><button>Submit & Lock Review</button></form><?php endif; ?><?php endif; ?></main>
<?php elseif($page==='review-invitation'): $me=require_login();$token=$_GET['token']??'';$hash=hash('sha256',$token);$q=db()->prepare('SELECT r.*,s.title FROM reviews r JOIN submissions s ON s.id=r.submission_id WHERE r.invitation_token_hash=? AND r.reviewer_id=? LIMIT 1');$q->execute([$hash,$me['id']]);$invite=$q->fetch(); ?>
<main class="wide content narrow"><h2>Review Invitation</h2><?php if(!$invite): ?><p>This review invitation is invalid or does not belong to your account.</p><?php else: ?><h3><?=e($invite['title'])?></h3><p>Status: <?=e($invite['status'])?></p><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="review-response"><input type="hidden" name="token" value="<?=e($token)?>"><button name="response" value="Accepted">Accept Review</button><button name="response" value="Declined">Decline Review</button></form><?php endif; ?></main>
<?php elseif($page==='editorial'): ?>
<main class="wide content"><h2>Editorial Team</h2>
<h3>EDITOR-IN-CHIEF</h3><p><strong>Dr. Olukayode Faleye</strong><br>Associate Professor, Edo State University, Iyamho</p>
<h3>CONSULTING EDITOR</h3><p><strong>Professor G. A. Vaaseh</strong></p>
<h3>EDITOR</h3><p><strong>Prof. Solomon Awuzie</strong><br>Edo State University, Iyamho</p>
<h3>MANAGING EDITOR</h3><p><strong>Matthew Alugbin, PhD</strong></p>
<h3>EDITORIAL ADVISORY BOARD</h3>
<p>Professor A. M. Okhakhu <span>(University of Benin)</span></p>
<p>Professor Andrew A. Ate <span>(Edo State University Iyamho)</span></p>
<p>Professor Afutendem Lucas Nkwetta <span>(University of Dschang, Cameroon)</span></p>
<p>Professor Andrew Ogah Ijwo <span>(Benue State University, Makurdi)</span></p>
<p>Professor Ayo Osisanwo <span>(University of Ibadan)</span></p>
<p>Professor Christoph Schmidt <span>(University of Applied Sciences, Bonn, Germany)</span></p>
<p>Professor Isidore Diala <span>(Imo State University)</span></p>
<p>Professor J. A. Sambe <span>(University of Veritas)</span></p>
<p>Professor P. F. Adebayo <span>(University of Ilorin)</span></p>
<p>Professor P. O. Alokan <span>(Joseph Ayo Babalola University)</span></p>
<p>Prof. Blessed Frederick Ngonso <span>(Edo State University, Iyamho)</span></p>
<p>Dr. Wilfred O. Olley <span>(Associate Professor, Edo State University, Iyamho)</span></p>
<p>Rev. Fr. Dr. Peter E. Egielewa <span>(Associate Professor, Edo State University, Iyamho)</span></p>
</main>
<?php elseif($page==='galley'): $name=basename($_GET['file']??'');if(!preg_match('/^na-\\d+-[a-f0-9]{24}\\.pdf$/',$name)){http_response_code(404);exit('Not Found');}$full=__DIR__.'/storage/uploads/'.$name;if(!is_file($full)){http_response_code(404);exit('Not Found');}header('Content-Type: application/pdf');header('Content-Length: '.filesize($full));header('Content-Disposition: inline; filename="'.$name.'"');readfile($full);exit; ?>
<?php elseif($page==='admin-overview'): $admin=require_login();if(!(has_role($admin,'Editor')||has_role($admin,'Journal Manager')||has_role($admin,'Site Administrator'))){http_response_code(403);exit('Access denied');}$my=(int)db()->query("SELECT COUNT(*) FROM submissions WHERE status NOT IN ('Published','Declined')")->fetchColumn();$un=(int)db()->query("SELECT COUNT(*) FROM submissions s WHERE status NOT IN ('Published','Declined') AND NOT EXISTS(SELECT 1 FROM reviews r WHERE r.submission_id=s.id)")->fetchColumn();$act=$my;$arc=(int)db()->query("SELECT COUNT(*) FROM submissions WHERE status IN ('Published','Declined')")->fetchColumn(); ?>
<style>
.ojs35{--nav:#263746;--nav2:#1f2d38;--blue:#006798;--line:#d5dadd;--bg:#f5f6f7;display:flex;min-height:100vh;background:var(--bg);font-family:Arial,Helvetica,sans-serif;color:#333}.ojs35 *{box-sizing:border-box}.ojs35-side{width:230px;background:var(--nav);color:#fff;flex:0 0 230px}.ojs35-logo{padding:22px 20px;border-bottom:1px solid #40515f;font-size:20px;font-weight:700}.ojs35-logo small{display:block;font-size:11px;color:#b9c5ce;margin-top:5px;font-weight:400}.ojs35-menu a{display:block;color:#dce5eb;text-decoration:none;padding:13px 20px;border-left:4px solid transparent}.ojs35-menu a:hover,.ojs35-menu a.on{background:var(--nav2);border-left-color:#4aa3d2;color:#fff}.ojs35-menu .sep{border-top:1px solid #40515f;margin:10px 0}.ojs35-main{flex:1;min-width:0}.ojs35-bar{height:64px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 28px}.ojs35-bar b{color:#4b5964}.ojs35-content{padding:28px;max-width:1400px}.ojs35 h1{font-size:28px;font-weight:400;margin:0 0 22px;color:#333}.ojs35-tabs{background:#fff;border:1px solid var(--line);border-bottom:0}.ojs35-tabs a{display:inline-block;padding:14px 20px;text-decoration:none;color:#536675;border-bottom:3px solid transparent}.ojs35-tabs a.on{color:var(--blue);border-bottom-color:var(--blue);font-weight:700}.ojs35-panel{background:#fff;border:1px solid var(--line);padding:20px;margin-bottom:18px}.ojs35-tools{display:flex;gap:10px;margin-bottom:16px}.ojs35-tools input,.ojs35-tools select{padding:9px;border:1px solid #bfc7cd}.ojs35 table{width:100%;border-collapse:collapse;background:#fff}.ojs35 th{font-size:12px;text-transform:uppercase;color:#647581;background:#f0f2f3;padding:12px;text-align:left;border-bottom:1px solid var(--line)}.ojs35 td{padding:14px 12px;border-bottom:1px solid #e2e6e8;vertical-align:top}.ojs35 .stage{font-size:12px;color:#687b89}.ojs35 .button,.ojs35 button{background:#0073aa;color:#fff;border:0;border-radius:3px;padding:9px 14px;text-decoration:none;cursor:pointer}.ojs35 label{display:block;margin-top:12px;font-weight:700}.ojs35 input,.ojs35 select,.ojs35 textarea{max-width:100%;padding:9px;border:1px solid #bbc4ca}.ojs35 textarea{width:100%;min-height:100px}.ojs35-grid{display:grid;grid-template-columns:minmax(0,1fr) 290px;gap:18px}.ojs35-card{background:#fff;border:1px solid var(--line);padding:18px}.ojs35-card h3{margin-top:0;font-size:17px}.ojs35-steps{display:flex;border-bottom:1px solid var(--line);background:#fff;margin-bottom:18px}.ojs35-steps a{flex:1;text-align:center;padding:14px;text-decoration:none;color:#566975;border-bottom:4px solid transparent}.ojs35-steps a.on{color:#006798;border-bottom-color:#006798;font-weight:700}@media(max-width:850px){.ojs35-side{width:190px;flex-basis:190px}.ojs35-grid{grid-template-columns:1fr}}
</style><div class="ojs35"><aside class="ojs35-side"><div class="ojs35-logo"><img src="assets/na-logo.svg" alt="NA" style="width:92px;height:58px;object-fit:contain;display:block;margin-bottom:8px">Nigerian Affairs<small>Editorial Management</small></div><nav class="ojs35-menu"><a class="on" href="?page=admin-overview">Dashboard</a><a href="?page=editor-submissions&queue=my">Submissions</a><a href="?page=issue-management">Issues</a><a href="?page=users-roles">Users & Roles</a><a href="?page=journal-settings">Settings</a><a href="?page=audit-report">Tools</a><div class="sep"></div><a href="./">View Site</a><a href="?page=logout">Log Out</a></nav></aside><section class="ojs35-main"><div class="ojs35-bar"><b>Nigerian Affairs</b><span><?=e($admin['given_name'])?> ▾</span></div><div class="ojs35-content"><h1>Dashboard</h1><div class="ojs35-tabs"><a class="on" href="?page=editor-submissions&queue=my">My Queue (<?=$my?>)</a><a href="?page=editor-submissions&queue=unassigned">Unassigned (<?=$un?>)</a><a href="?page=editor-submissions&queue=active">All Active (<?=$act?>)</a><a href="?page=editor-submissions&queue=archives">Archives (<?=$arc?>)</a></div><div class="ojs35-panel"><h3>Editorial Tasks</h3><p>Use the submission queues to manage manuscripts through Submission, Review, Copyediting and Production.</p><a class="button" href="?page=editor-submissions&queue=my">Open My Queue</a></div></div></section></div>
<?php elseif($page==='users-roles'): $admin=require_login();if(!(has_role($admin,'Journal Manager')||has_role($admin,'Site Administrator'))){http_response_code(403);exit('Access denied');}$users=db()->query('SELECT * FROM users ORDER BY created_at DESC')->fetchAll(); ?>
<main class="wide content"><h2>Users & Roles</h2><?php foreach($users as $usr): ?><div class="paper"><strong><?=e($usr['given_name'].' '.$usr['family_name'])?></strong> · <?=e($usr['email'])?><br>Verified: <?=((int)$usr['verified']?'Yes':'No')?> · Roles: <?=e($usr['roles'])?><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="update-user-role"><input type="hidden" name="user_id" value="<?=(int)$usr['id']?>"><?php foreach(['Reader','Author','Reviewer','Editor','Journal Manager'] as $role): ?><label><input type="checkbox" name="roles[]" value="<?=e($role)?>" <?=has_role($usr,$role)?'checked':''?>> <?=e($role)?></label><?php endforeach; ?><button>Save Roles</button></form><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="set-user-verification"><input type="hidden" name="user_id" value="<?=(int)$usr['id']?>"><input type="hidden" name="verified" value="<?=((int)$usr['verified']?0:1)?>"><button><?=((int)$usr['verified']?'Mark Unverified':'Verify User')?></button></form></div><?php endforeach; ?></main>
<?php elseif($page==='journal-settings'): $admin=require_login();if(!(has_role($admin,'Journal Manager')||has_role($admin,'Site Administrator'))){http_response_code(403);exit('Access denied');}$settings=[];foreach(db()->query('SELECT setting_key,setting_value FROM journal_settings')->fetchAll() as $st)$settings[$st['setting_key']]=$st['setting_value']; ?>
<main class="wide content"><h2>Journal Settings</h2><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save-settings"><label>Journal Name</label><input name="journal_name" value="<?=e($settings['journal_name']??'Nigerian Affairs')?>"><label>Publisher</label><input name="publisher" value="<?=e($settings['publisher']??'Faculty of Arts and Communication, Edo State University, Iyamho')?>"><label>ISSN</label><input name="issn" value="<?=e($settings['issn']??'')?>"><label>Frequency</label><input name="frequency" value="<?=e($settings['frequency']??'May and November')?>"><label>Contact Email</label><input type="email" name="contact_email" value="<?=e($settings['contact_email']??'editor@nigeriaaffairs.com')?>"><button>Save Settings</button></form></main>
<?php elseif($page==='audit-report'): $admin=require_login();if(!(has_role($admin,'Journal Manager')||has_role($admin,'Site Administrator'))){http_response_code(403);exit('Access denied');}$logs=db()->query('SELECT a.*,u.email FROM audit_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 250')->fetchAll(); ?>
<main class="wide content"><h2>Audit Report</h2><?php foreach($logs as $log): ?><div class="paper"><strong><?=e($log['action'])?></strong><br><?=e($log['email']??'System')?> · <?=e($log['created_at'])?><?php if(!empty($log['submission_id'])): ?> · Submission #<?=(int)$log['submission_id']?><?php endif; ?></div><?php endforeach; ?></main>
<?php elseif($page==='issue-management'): $admin=require_login();if(!(has_role($admin,'Editor')||has_role($admin,'Journal Manager')||has_role($admin,'Site Administrator'))){http_response_code(403);exit('Access denied');}$issues=db()->query('SELECT * FROM issues ORDER BY year DESC,volume DESC,number DESC')->fetchAll(); ?>
<main class="wide content"><h2>Issues</h2><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="create-issue"><label>Volume</label><input type="number" name="volume" min="1" required><label>Number</label><input type="number" name="number" min="1" required><label>Year</label><input type="number" name="year" min="2000" required><label>Issue Title</label><input name="title"><label>Description</label><textarea name="description"></textarea><button>Create Issue</button></form><h3>Existing Issues</h3><?php foreach($issues as $i): ?><div class="paper"><b>Vol. <?=(int)$i['volume']?> No. <?=(int)$i['number']?> (<?=(int)$i['year']?>)</b> <?=e($i['title']??'')?> · <?=e($i['status'])?><?php if($i['status']!=='Published'): ?><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="publish-issue"><input type="hidden" name="issue_id" value="<?=(int)$i['id']?>"><button>Publish Issue</button></form><?php endif; ?></div><?php endforeach; ?></main>
<?php elseif($page==='announcement-management'): $admin=require_login();if(!(has_role($admin,'Editor')||has_role($admin,'Journal Manager')||has_role($admin,'Site Administrator'))){http_response_code(403);exit('Access denied');}$ans=db()->query('SELECT * FROM announcements ORDER BY created_at DESC')->fetchAll(); ?>
<main class="wide content"><h2>Announcements</h2><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="publish-announcement"><label>Title</label><input name="title" required><label>Announcement</label><textarea name="body" required></textarea><button>Publish Announcement</button></form><?php foreach($ans as $an): ?><div class="paper"><b><?=e($an['title'])?></b><br><?=e($an['published_at']??'Draft')?></div><?php endforeach; ?></main>
<?php elseif($page==='galley-management'): $admin=require_login();if(!(has_role($admin,'Editor')||has_role($admin,'Journal Manager')||has_role($admin,'Site Administrator'))){http_response_code(403);exit('Access denied');}$pubs=db()->query("SELECT id,title FROM submissions WHERE status='Published' OR stage='Production' ORDER BY updated_at DESC")->fetchAll(); ?>
<main class="wide content"><h2>Publication Galleys</h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="add-galley"><label>Article</label><select name="submission_id" required><option value="">Select article</option><?php foreach($pubs as $p): ?><option value="<?=(int)$p['id']?>"><?=e($p['title'])?></option><?php endforeach; ?></select><label>Label</label><input name="label" value="PDF"><label>PDF Galley</label><input type="file" name="galley_pdf" accept="application/pdf,.pdf" required><small>PDF only. Maximum 25 MB.</small><button>Upload Galley</button></form></main>
<?php elseif($page==='search'): $term=trim($_GET['q']??'');$results=[];if($term!==''){$q=db()->prepare("SELECT s.id,s.title,s.authors,s.abstract,p.issue_label,p.pages FROM submissions s JOIN production_items p ON p.submission_id=s.id WHERE s.status='Published' AND (s.title LIKE ? OR s.authors LIKE ? OR s.abstract LIKE ? OR s.keywords LIKE ?) ORDER BY p.published_at DESC");$like='%'.$term.'%';$q->execute([$like,$like,$like,$like]);$results=$q->fetchAll();} ?>
<main class="wide content"><h2>Search</h2><form method="get"><input type="hidden" name="page" value="search"><label>Search published articles</label><input name="q" value="<?=e($term)?>" placeholder="Title, author, abstract or keyword"><button>Search</button></form><?php if($term!==''): ?><h3>Search Results</h3><?php if(!$results): ?><p>No results found.</p><?php endif; ?><?php foreach($results as $r): ?><article class="paper"><h3><a href="?page=article&id=<?=(int)$r['id']?>"><?=e($r['title'])?></a></h3><p><?=e($r['authors'])?></p><p><?=e($r['issue_label']??'')?> · <?=e($r['pages']??'')?></p></article><?php endforeach; ?><?php endif; ?></main>
<?php elseif($page==='announcements'): $ans=db()->query("SELECT * FROM announcements WHERE published_at IS NOT NULL ORDER BY published_at DESC")->fetchAll(); ?>
<main class="wide content"><h2>Announcements</h2><?php if(!$ans): ?><p>No announcements have been published yet.</p><?php endif; ?><?php foreach($ans as $an): ?><article class="paper"><h3><?=e($an['title'])?></h3><small><?=e(substr($an['published_at'],0,10))?></small><p><?=nl2br(e($an['body']))?></p></article><?php endforeach; ?></main>
<?php elseif($page==='article'): $aid=(int)($_GET['id']??0);$q=db()->prepare("SELECT s.*,p.issue_label,p.pages,p.doi,p.published_at FROM submissions s JOIN production_items p ON p.submission_id=s.id WHERE s.id=? AND s.status='Published' AND p.published_at IS NOT NULL");$q->execute([$aid]);$a=$q->fetch(); ?>
<?php if(!$a): ?><main class="wide content"><h2>Article not found</h2></main><?php else: ?><?php $vol='';$num='';if(preg_match('/Vol\\.?\\s*(\\d+).*?No\\.?\\s*(\\d+)/i',$a['issue_label']??'',$im)){$vol=$im[1];$num=$im[2];}$first='';$last='';if(preg_match('/(\\d+)\\s*[-–]\\s*(\\d+)/u',$a['pages']??'',$pm)){$first=$pm[1];$last=$pm[2];}$gqmeta=db()->prepare("SELECT file_path FROM galleys WHERE submission_id=? AND mime_type='application/pdf' ORDER BY id DESC LIMIT 1");$gqmeta->execute([$a['id']]);$pdf=$gqmeta->fetchColumn();$base=rtrim(getenv('APP_URL')?:'', '/');$canonical=$base.'/?page=article&id='.(int)$a['id'];$pdfUrl=$pdf?($base.'/'.ltrim($pdf,'/')):''; ?>
<head><link rel="canonical" href="<?=e($canonical)?>"><meta name="citation_title" content="<?=e($a['title'])?>"><meta name="citation_journal_title" content="Nigerian Affairs"><meta name="citation_publication_date" content="<?=e(substr($a['published_at'],0,10))?>"><?php foreach(array_filter(array_map('trim',explode(',',$a['authors']))) as $ca): ?><meta name="citation_author" content="<?=e($ca)?>"><?php endforeach; ?><?php if($vol): ?><meta name="citation_volume" content="<?=e($vol)?>"><?php endif; ?><?php if($num): ?><meta name="citation_issue" content="<?=e($num)?>"><?php endif; ?><?php if($first): ?><meta name="citation_firstpage" content="<?=e($first)?>"><?php endif; ?><?php if($last): ?><meta name="citation_lastpage" content="<?=e($last)?>"><?php endif; ?><?php if($a['doi']): ?><meta name="citation_doi" content="<?=e($a['doi'])?>"><?php endif; ?><?php if($pdfUrl): ?><meta name="citation_pdf_url" content="<?=e($pdfUrl)?>"><?php endif; ?><meta name="citation_abstract_html_url" content="<?=e($canonical)?>"><meta name="citation_language" content="<?=e($a['language']?:'English')?>"></head>
<main class="wide layout"><section><p><?=e($a['issue_label']??'')?></p><h2><?=e($a['title'])?></h2><p><strong><?=e($a['authors'])?></strong></p><h3>Abstract</h3><p><?=nl2br(e($a['abstract']))?></p><p><strong>Keywords:</strong> <?=e($a['keywords'])?></p><p><strong>Pages:</strong> <?=e($a['pages']??'')?><?php if($a['doi']): ?><br><strong>DOI:</strong> <?=e($a['doi'])?><?php endif; ?></p><?php $gq=db()->prepare("SELECT * FROM galleys WHERE submission_id=? ORDER BY id");$gq->execute([$a['id']]);foreach($gq->fetchAll() as $g): ?><p><a href="<?=e($g['file_path'])?>" target="_blank" rel="noopener"><?=e($g['label'])?></a></p><?php endforeach; ?><h3>How to Cite</h3><p><?=e($a['authors'])?> (<?=e(substr($a['published_at'],0,4))?>). <?=e($a['title'])?>. <em>Nigerian Affairs</em><?=($a['pages']?' , '.$a['pages']:'')?>.</p></section><aside><h3>Article Details</h3><p>Published: <?=e(substr($a['published_at'],0,10))?></p><p>Section: <?=e($a['section'])?></p></aside></main><?php endif; ?>
<?php elseif($page==='current'): $q=db()->query("SELECT i.id,i.volume,i.number,i.year,i.title,i.published_at,CONCAT('Vol. ',i.volume,' No. ',i.number,' (',i.year,')') issue_label FROM issues i WHERE i.status='Published' AND EXISTS (SELECT 1 FROM production_items p JOIN submissions s ON s.id=p.submission_id WHERE s.status='Published' AND p.issue_label=CONCAT('Vol. ',i.volume,' No. ',i.number,' (',i.year,')')) ORDER BY i.published_at DESC,i.year DESC,i.volume DESC,i.number DESC LIMIT 1");$issue=$q->fetch(); ?>
<main class="wide content"><h2>Current</h2><?php if(!$issue): ?><p>No published issue is available yet.</p><?php else: ?><h3><?=e($issue['issue_label'])?></h3><?php $q=db()->prepare("SELECT s.id,s.title,s.authors,p.pages,p.doi FROM submissions s JOIN production_items p ON p.submission_id=s.id WHERE s.status='Published' AND p.issue_label=? ORDER BY p.published_at,p.id");$q->execute([$issue['issue_label']]);foreach($q->fetchAll() as $a): ?><article class="paper"><h3><a href="?page=article&id=<?=(int)$a['id']?>"><?=e($a['title'])?></a></h3><p><?=e($a['authors'])?></p><p><?=e($a['pages']??'')?><?php if($a['doi']): ?> · <?=e($a['doi'])?><?php endif; ?></p></article><?php endforeach; ?><?php endif; ?></main>
<?php elseif($page==='archives'): $issues=db()->query("SELECT p.issue_label,MAX(p.published_at) latest,COUNT(*) articles FROM production_items p JOIN submissions s ON s.id=p.submission_id WHERE s.status='Published' GROUP BY p.issue_label ORDER BY latest DESC")->fetchAll(); ?>
<main class="wide content"><h2>Archives</h2><?php if(!$issues): ?><p>No archived issues yet.</p><?php endif; ?><?php foreach($issues as $i): ?><div class="paper"><h3><?=e($i['issue_label'])?></h3><p><?=e(substr($i['latest'],0,10))?> · <?=(int)$i['articles']?> article(s)</p><?php $q=db()->prepare("SELECT s.id,s.title,s.authors FROM submissions s JOIN production_items p ON p.submission_id=s.id WHERE s.status='Published' AND p.issue_label=? ORDER BY p.published_at,p.id");$q->execute([$i['issue_label']]);foreach($q->fetchAll() as $a): ?><p><a href="?page=article&id=<?=(int)$a['id']?>"><?=e($a['title'])?></a><br><?=e($a['authors'])?></p><?php endforeach; ?></div><?php endforeach; ?></main>
<?php elseif($page==='home'): ?>
<div class="hero wide"></div><main class="wide layout"><section><h2>Announcements</h2><div class="announce"><?php $ha=db()->query("SELECT * FROM announcements WHERE published_at IS NOT NULL ORDER BY published_at DESC LIMIT 2")->fetchAll();if(!$ha): ?><p>No announcements have been published yet.</p><?php endif; ?><?php foreach($ha as $an): ?><article><a href="?page=announcements"><?=e($an['title'])?></a><small><?=e(substr($an['published_at'],0,10))?></small><p><?=e(mb_strimwidth(strip_tags($an['body']),0,180,'…','UTF-8'))?></p></article><?php endforeach; ?></div><hr><h2>Current issue</h2><?php $hq=db()->query("SELECT i.volume,i.number,i.year,i.published_at,CONCAT('Vol. ',i.volume,' No. ',i.number,' (',i.year,')') issue_label FROM issues i WHERE i.status='Published' AND EXISTS (SELECT 1 FROM production_items p JOIN submissions s ON s.id=p.submission_id WHERE s.status='Published' AND p.issue_label=CONCAT('Vol. ',i.volume,' No. ',i.number,' (',i.year,')')) ORDER BY i.published_at DESC,i.year DESC,i.volume DESC,i.number DESC LIMIT 1");$hi=$hq->fetch();if($hi): ?><p><b><a href="?page=current"><?=e($hi['issue_label'])?></a></b></p><p>Published: <?=e(substr($hi['published_at'],0,10))?></p><?php else: ?><p>No published issue is available yet.</p><?php endif; ?></section><aside><h3>Information</h3><a>For Readers</a><a>For Authors</a><a>For Librarians</a><hr><a class="button" href="?page=submissions">Make a Submission</a><h3>Journal Details</h3><p>Frequency<br><b>Biannual</b></p><p>Review<br><b>Double-blind</b></p></aside></main>
<?php else: ?><main class="wide content"><h2><?=e(ucwords(str_replace('-',' ',$page)))?></h2><p>Nigerian Affairs is an interdisciplinary academic journal published by the Faculty of Arts and Communication, Edo State University Iyamho, Nigeria.</p></main><?php endif; ?>
<?php if(!$adminChrome): ?><footer><div class="wide cols"><div><h3>Nigerian Affairs</h3><p>Faculty of Arts and Communication, Edo State University Iyamho, Nigeria.</p></div><div><h3>Journal Details</h3><p>Biannual · May and November<br>Double-blind peer review</p></div><div><h3>Information</h3><p>For Readers<br>For Authors<br>For Librarians</p></div><div><h3>Contact</h3><p>Edo State University Iyamho<br>Edo State, Nigeria</p></div></div></footer><?php endif; ?></body></html>