<?php
require __DIR__.'/config.php';
$page=$_GET['page']??'home';$msg='';$u=current_user();
if($page==='logout'){session_destroy();header('Location: ./');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();$a=$_POST['action']??'';try{
 if($a==='register'){$email=strtolower(trim($_POST['email']??''));$username=trim($_POST['username']??'');$pw=$_POST['password']??'';if(!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($username)<3||strlen($pw)<8)throw new RuntimeException('Enter a valid email, username and password of at least 8 characters.');$s=db()->prepare('INSERT INTO users(email,username,password_hash,given_name,family_name,affiliation,country,orcid,reviewing_interests,roles,verified) VALUES(?,?,?,?,?,?,?,?,?,?,1)');$s->execute([$email,$username,password_hash($pw,PASSWORD_DEFAULT),trim($_POST['given_name']),trim($_POST['family_name']),trim($_POST['affiliation']),trim($_POST['country']),trim($_POST['orcid']),trim($_POST['reviewing_interests']),'Author,Reader']);$msg='Registration successful. You can now log in.';$page='login';}
 elseif($a==='login'){$id=trim($_POST['identity']??'');$s=db()->prepare('SELECT * FROM users WHERE email=? OR username=? LIMIT 1');$s->execute([strtolower($id),$id]);$x=$s->fetch();if(!$x||!password_verify($_POST['password']??'',$x['password_hash']))throw new RuntimeException('Invalid username/email or password.');session_regenerate_id(true);$_SESSION['uid']=$x['id'];header('Location: ?page=dashboard');exit;}
 elseif($a==='submit'){$me=require_login();$s=db()->prepare('INSERT INTO submissions(author_id,title,authors,abstract,keywords,section,language,references_text) VALUES(?,?,?,?,?,?,?,?)');$s->execute([$me['id'],trim($_POST['title']),trim($_POST['authors']),trim($_POST['abstract']),trim($_POST['keywords']),$_POST['section'],$_POST['language'],trim($_POST['references'])]);$sid=(int)db()->lastInsertId();db()->prepare('INSERT INTO audit_log(user_id,submission_id,action) VALUES(?,?,?)')->execute([$me['id'],$sid,'Submission created']);header('Location: ?page=dashboard');exit;}
}catch(Throwable $ex){$msg=$ex->getMessage();}
$u=current_user();
function top(string $title):void{global $u;?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> | Nigerian Affairs</title><link rel="stylesheet" href="assets/style.css"></head><body><div class="utility"><div class="wide"><span>English</span><span><?php if($u):?><a href="?page=dashboard">Dashboard</a> · <a href="?page=logout">Logout</a><?php else:?><a href="?page=register">Register</a> · <a href="?page=login">Login</a><?php endif;?></span></div></div><header><div class="wide brand"><div class="logo">NA</div><div><h1>Nigerian Affairs</h1><small>ARTS · HUMANITIES · SOCIAL SCIENCES</small></div></div><nav class="wide"><a href="./">Home</a><a href="?page=about">About the journal</a><a href="?page=current">Current</a><a href="?page=policies">Journal Policies</a><a href="?page=editorial">Editorial Team</a><a href="?page=submissions">Instructions to Authors</a><a href="?page=archives">Archives</a><a href="?page=contact">Contact</a></nav></header><?php}
function bottom():void{?><footer><div class="wide cols"><div><h3>Nigerian Affairs</h3><p>Faculty of Arts and Communication, Edo State University Iyamho, Nigeria.</p></div><div><h3>Journal Details</h3><p>Biannual · May and November<br>Double-blind peer review</p></div><div><h3>Information</h3><p>For Readers<br>For Authors<br>For Librarians</p></div><div><h3>Contact</h3><p>Edo State University Iyamho<br>Edo State, Nigeria</p></div></div></footer></body></html><?php}
top(ucfirst($page));if($msg)echo '<div class="wide alert">'.e($msg).'</div>';
if($page==='login'){?><main class="wide content narrow"><h2>Login</h2><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="login"><label>Username or Email</label><input name="identity" required autofocus><label>Password</label><input type="password" name="password" required><label class="check"><input type="checkbox"> Keep me logged in</label><button>Login</button></form><p><a href="?page=register">Not a user? Register with this site</a></p><p><a href="?page=forgot">Forgot your password?</a></p></main><?php}
elseif($page==='register'){?><main class="wide content narrow"><h2>Register</h2><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="register"><label>Given Name</label><input name="given_name" required><label>Family Name</label><input name="family_name" required><label>Affiliation</label><input name="affiliation"><label>Country</label><input name="country"><label>Email</label><input type="email" name="email" required><label>Username</label><input name="username" required><label>Password</label><input type="password" name="password" minlength="8" required><label>ORCID iD</label><input name="orcid"><label>Reviewing interests</label><textarea name="reviewing_interests"></textarea><button>Register</button></form></main><?php}
elseif($page==='dashboard'){$me=require_login();$q=db()->prepare('SELECT * FROM submissions WHERE author_id=? ORDER BY created_at DESC');$q->execute([$me['id']]);$subs=$q->fetchAll();?><main class="wide content"><h2>Dashboard</h2><p><?=e($me['given_name'].' '.$me['family_name'])?> · <?=e($me['roles'])?></p><a class="button" href="?page=submissions">New Submission</a><?php if(has_role($me,'Editor')||has_role($me,'Journal Manager')||has_role($me,'Site Administrator')):?><a class="button" href="?page=editor">Editorial Workflow</a><?php endif;?><h3>My Submissions</h3><?php if(!$subs):?><p>No submissions.</p><?php endif;foreach($subs as $s):?><div class="paper"><b><?=e($s['title'])?></b><br><?=e($s['stage'])?> · <?=e($s['status'])?></div><?php endforeach;?></main><?php}
elseif($page==='submissions'){require_login();?><main class="wide content"><h2>New Submission</h2><div class="steps">1. Start　 2. Upload Submission　 3. Enter Metadata　 4. Confirmation　 5. Next Steps</div><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="submit"><label>Manuscript title</label><input name="title" required><label>Authors</label><input name="authors" required><label>Abstract</label><textarea name="abstract" required></textarea><label>Keywords</label><input name="keywords" required><label>Section</label><select name="section"><option>Research Article</option><option>Review Article</option><option>Commentary</option></select><label>Language</label><select name="language"><option>English</option></select><label>References</label><textarea name="references"></textarea><button>Save and Continue</button></form></main><?php}
elseif($page==='editor'){$me=require_login();if(!(has_role($me,'Editor')||has_role($me,'Journal Manager')||has_role($me,'Site Administrator'))){http_response_code(403);?><main class="wide content"><h2>Access denied</h2></main><?php}else{$subs=db()->query('SELECT s.*,u.given_name,u.family_name FROM submissions s JOIN users u ON u.id=s.author_id ORDER BY s.created_at DESC')->fetchAll();?><main class="wide content"><h2>Editorial Workflow</h2><p>Submission · Review · Copyediting · Production</p><?php foreach($subs as $s):?><div class="paper"><b><?=e($s['title'])?></b><br>Author: <?=e($s['given_name'].' '.$s['family_name'])?><br><?=e($s['stage'])?> · <?=e($s['status'])?></div><?php endforeach;?></main><?php}}
elseif($page==='home'){?><div class="hero wide"></div><main class="wide layout"><section><h2>Announcements</h2><div class="announce"><article><a>Call for papers: Nigerian Affairs</a><small>2026-09-18</small><p>Nigerian Affairs welcomes original scholarship across the Arts, Humanities and Social Sciences.</p></article><article><a>Volume 2, Number 1 (2026) published online</a><small>2026-09-18</small><p>The current issue of Nigerian Affairs is now available.</p></article></div><hr><h2>Current issue</h2><p><b>Vol. 2 No. 1 (2026): Nigerian Affairs</b></p><p>Published: 2026-09-18</p></section><aside><h3>Information</h3><a>For Readers</a><a>For Authors</a><a>For Librarians</a><hr><a class="button" href="?page=submissions">Make a Submission</a><h3>Journal Details</h3><p>Frequency<br><b>Biannual</b></p><p>Review<br><b>Double-blind</b></p></aside></main><?php}
else{?><main class="wide content"><h2><?=e(ucwords(str_replace('-',' ',$page)))?></h2><p>Nigerian Affairs is an interdisciplinary academic journal published by the Faculty of Arts and Communication, Edo State University Iyamho, Nigeria.</p></main><?php}bottom();