CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(190) UNIQUE NOT NULL,
 username VARCHAR(80) UNIQUE NOT NULL,
 password_hash VARCHAR(255) NOT NULL,
 given_name VARCHAR(100) NOT NULL,
 family_name VARCHAR(100) NOT NULL,
 affiliation VARCHAR(190) NULL,
 country VARCHAR(100) NULL,
 orcid VARCHAR(30) NULL,
 reviewing_interests TEXT NULL,
 roles VARCHAR(255) NOT NULL DEFAULT 'Author,Reader',
 verified TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS submissions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 author_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(500) NOT NULL,
 authors TEXT NOT NULL,
 abstract TEXT NOT NULL,
 keywords TEXT NOT NULL,
 section VARCHAR(80) NOT NULL,
 language VARCHAR(40) NOT NULL DEFAULT 'English',
 references_text MEDIUMTEXT NULL,
 stage VARCHAR(80) NOT NULL DEFAULT 'Submission',
 status VARCHAR(120) NOT NULL DEFAULT 'Awaiting editorial screening',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(author_id)
);
CREATE TABLE IF NOT EXISTS reviews (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 submission_id BIGINT UNSIGNED NOT NULL,
 reviewer_id BIGINT UNSIGNED NULL,
 status VARCHAR(80) NOT NULL DEFAULT 'Invited',
 recommendation VARCHAR(120) NULL,
 comments_to_author MEDIUMTEXT NULL,
 comments_to_editor MEDIUMTEXT NULL,
 invitation_token_hash CHAR(64) NULL,
 due_at DATETIME NULL,
 responded_at DATETIME NULL,
 submitted_at DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS decisions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 submission_id BIGINT UNSIGNED NOT NULL,
 editor_id BIGINT UNSIGNED NOT NULL,
 decision VARCHAR(120) NOT NULL,
 note MEDIUMTEXT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS audit_log (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NULL,
 submission_id BIGINT UNSIGNED NULL,
 action VARCHAR(255) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS password_resets (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 token_hash CHAR(64) NOT NULL UNIQUE,
 expires_at DATETIME NOT NULL,
 used_at DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(user_id), INDEX(expires_at)
);

CREATE TABLE IF NOT EXISTS email_verifications (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,token_hash CHAR(64) NOT NULL UNIQUE,expires_at DATETIME NOT NULL,used_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(user_id),INDEX(expires_at)
);


CREATE TABLE IF NOT EXISTS revisions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 submission_id BIGINT UNSIGNED NOT NULL,
 author_id BIGINT UNSIGNED NOT NULL,
 response_to_reviewers MEDIUMTEXT NOT NULL,
 revised_title VARCHAR(500) NULL,
 revised_abstract MEDIUMTEXT NULL,
 status VARCHAR(80) NOT NULL DEFAULT 'Submitted',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(submission_id), INDEX(author_id)
);
CREATE TABLE IF NOT EXISTS production_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 submission_id BIGINT UNSIGNED NOT NULL UNIQUE,
 copyediting_status VARCHAR(80) NOT NULL DEFAULT 'Not started',
 production_status VARCHAR(80) NOT NULL DEFAULT 'Not started',
 issue_label VARCHAR(190) NULL,
 pages VARCHAR(40) NULL,
 doi VARCHAR(255) NULL,
 published_at DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS issues (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 volume INT NOT NULL,
 number INT NOT NULL,
 year INT NOT NULL,
 title VARCHAR(255) NULL,
 description MEDIUMTEXT NULL,
 status VARCHAR(40) NOT NULL DEFAULT 'Future',
 published_at DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY issue_identity(volume,number,year)
);
CREATE TABLE IF NOT EXISTS announcements (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(255) NOT NULL,
 body MEDIUMTEXT NOT NULL,
 published_at DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS galleys (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 submission_id BIGINT UNSIGNED NOT NULL,
 label VARCHAR(40) NOT NULL DEFAULT 'PDF',
 file_path VARCHAR(500) NOT NULL,
 mime_type VARCHAR(100) NOT NULL DEFAULT 'application/pdf',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(submission_id)
);

CREATE TABLE IF NOT EXISTS journal_settings (
 setting_key VARCHAR(100) PRIMARY KEY,
 setting_value MEDIUMTEXT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS submission_files (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 submission_id BIGINT UNSIGNED NOT NULL,
 uploaded_by BIGINT UNSIGNED NOT NULL,
 file_stage VARCHAR(40) NOT NULL DEFAULT 'Submission',
 file_role VARCHAR(60) NOT NULL DEFAULT 'Original Manuscript',
 original_name VARCHAR(255) NOT NULL,
 stored_name VARCHAR(255) NOT NULL UNIQUE,
 mime_type VARCHAR(100) NOT NULL,
 file_size BIGINT UNSIGNED NOT NULL,
 version_no INT NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(submission_id), INDEX(uploaded_by)
);
