import mysql from 'mysql2/promise';

const pool=mysql.createPool({host:Bun.env.MYSQLHOST,user:Bun.env.MYSQLUSER,password:Bun.env.MYSQLPASSWORD,database:Bun.env.MYSQLDATABASE,port:Number(Bun.env.MYSQLPORT||3306),waitForConnections:true,connectionLimit:2});
const P='SYNTHETIC-NA-AUDIT-20260924';
const pass=[];
const ok=(s,d)=>{pass.push(s);console.log('[PASS] '+s+': '+d)};
let c,v;
try{
 c=await pool.getConnection();await c.beginTransaction();
 const req=['users','submissions','submission_files','submission_editors','reviews','decisions','revisions','production_items','issues','galleys','apc_payments','payment_evidence','submission_authors','audit_log','journal_settings'];
 const [ts]=await c.query('SELECT table_name FROM information_schema.tables WHERE table_schema=?',[Bun.env.MYSQLDATABASE]);const have=new Set(ts.map(r=>r.TABLE_NAME||r.table_name));const miss=req.filter(x=>!have.has(x));if(miss.length)throw new Error('Missing tables: '+miss.join(', '));ok('schema','required workflow tables present');
 const user=async(suffix,roles)=>{const email=(P+'-'+suffix+'@example.invalid').toLowerCase();const username=(P+'_'+suffix).toLowerCase().replace(/[^a-z0-9_]/g,'_');await c.execute('INSERT INTO users(email,username,password_hash,given_name,family_name,affiliation,country,orcid,reviewing_interests,roles,verified) VALUES(?,?,?,?,?,?,?,?,?,?,1)',[email,username,'synthetic','Synthetic',suffix,'Synthetic University','Nigeria','',P,roles]);const [r]=await c.execute('SELECT id FROM users WHERE email=?',[email]);return {id:r[0].id,email}};
 const a=await user('author','Author,Reader'),r=await user('reviewer','Reviewer,Reader'),e=await user('editor','Editor,Author,Reader'),m=await user('manager','Journal Manager,Editor,Author,Reader');ok('users','author/reviewer/editor/manager created');
 const title=P+': Workflow Verification';await c.execute("INSERT INTO submissions(author_id,title,authors,abstract,keywords,section,language,references_text,stage,status) VALUES(?,?,?,?,?,?,?,?,'Submission','Awaiting editorial screening')",[a.id,title,'Synthetic Author; Synthetic Coauthor','Synthetic rollback-only abstract','synthetic,test,workflow','Research Article','English','Synthetic references']);const [sr]=await c.execute('SELECT id FROM submissions WHERE title=?',[title]);const sid=sr[0].id;ok('submission','submission '+sid+' created');
 const [u0]=await c.execute("SELECT COUNT(*) c FROM submissions s WHERE s.id=? AND s.status NOT IN ('Published','Declined') AND NOT EXISTS(SELECT 1 FROM submission_editors se WHERE se.submission_id=s.id)",[sid]);if(Number(u0[0].c)!==1)throw new Error('Unassigned queue failed');await c.execute('INSERT INTO submission_editors(submission_id,editor_id,assigned_by) VALUES(?,?,?)',[sid,e.id,m.id]);const [mq]=await c.execute("SELECT COUNT(*) c FROM submissions s JOIN submission_editors se ON se.submission_id=s.id WHERE s.id=? AND se.editor_id=? AND s.status NOT IN ('Published','Declined')",[sid,e.id]);if(Number(mq[0].c)!==1)throw new Error('My Queue failed');ok('editor_assignment','My Queue and Unassigned semantics verified');
 await c.execute('INSERT INTO submission_files(submission_id,uploaded_by,file_stage,file_role,original_name,stored_name,mime_type,file_size,version_no) VALUES(?,?,?,?,?,?,?,?,?)',[sid,a.id,'Submission','Review File',P+'-review.docx',P+'-'+sid+'-review.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',1024,1]);await c.execute("INSERT INTO reviews(submission_id,reviewer_id,status,recommendation,comments_to_author,comments_to_editor,due_at,responded_at,submitted_at) VALUES(?,?,'Submitted','Revisions Required','Synthetic author comments','Synthetic editor comments',DATE_ADD(NOW(),INTERVAL 7 DAY),NOW(),NOW())",[sid,r.id]);await c.execute("UPDATE submissions SET stage='Review',status='Review submitted' WHERE id=?",[sid]);ok('peer_review','review file and submitted review created');
 await c.execute('INSERT INTO decisions(submission_id,editor_id,decision,note) VALUES(?,?,?,?)',[sid,e.id,'Revisions Required',P+' revision']);await c.execute("UPDATE submissions SET stage='Submission',status='Revision requested' WHERE id=?",[sid]);await c.execute("INSERT INTO revisions(submission_id,author_id,response_to_reviewers,revised_title,revised_abstract,status) VALUES(?,?,?,?,?,'Submitted')",[sid,a.id,P+' response',P+': Revised','Synthetic revised abstract']);await c.execute('INSERT INTO submission_files(submission_id,uploaded_by,file_stage,file_role,original_name,stored_name,mime_type,file_size,version_no) VALUES(?,?,?,?,?,?,?,?,?)',[sid,a.id,'Revision','Revised Manuscript',P+'-revision.docx',P+'-'+sid+'-revision.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',2048,2]);await c.execute("UPDATE submissions SET stage='Review',status='Revision submitted' WHERE id=?",[sid]);ok('revision','revision and v2 file metadata created');
 await c.execute('INSERT INTO decisions(submission_id,editor_id,decision,note) VALUES(?,?,?,?)',[sid,e.id,'Accept Submission',P+' acceptance']);await c.execute("UPDATE submissions SET stage='Copyediting',status='Accepted' WHERE id=?",[sid]);await c.execute("INSERT INTO production_items(submission_id,copyediting_status,production_status) VALUES(?,'Complete','In production')",[sid]);await c.execute("UPDATE submissions SET stage='Production',status='In production' WHERE id=?",[sid]);ok('production','acceptance, copyediting and Production transition verified');
 const issueTitle=P+': Test Issue';await c.execute("INSERT INTO issues(volume,number,year,title,description,status,published_at) VALUES(999,24,2026,?,?,'Published',NOW())",[issueTitle,'Synthetic rollback-only issue']);const [ir]=await c.execute('SELECT id FROM issues WHERE title=?',[issueTitle]);const iid=ir[0].id,il='Vol. 999 No. 24 (2026)';await c.execute('INSERT INTO galleys(submission_id,label,file_path,mime_type) VALUES(?,?,?,?)',[sid,'PDF','?page=galley&file=na-'+sid+'-synthetic.pdf','application/pdf']);
 await c.execute("INSERT INTO apc_payments(submission_id,payment_type,amount,reference_no,status,evidence_note,verified_by,verified_at) VALUES(?,'Publication fee',30000,?,'Verified','Synthetic verified evidence',?,NOW())",[sid,P+'-PAY',m.id]);const [pr]=await c.execute('SELECT id FROM apc_payments WHERE reference_no=?',[P+'-PAY']);await c.execute('INSERT INTO payment_evidence(payment_id,submitted_by,original_name,stored_name,mime_type,file_size) VALUES(?,?,?,?,?,?)',[pr[0].id,a.id,P+'-receipt.pdf',P+'-receipt.pdf','application/pdf',512]);const [gt]=await c.execute("SELECT COUNT(*) c FROM apc_payments WHERE submission_id=? AND payment_type='Publication fee' AND status IN ('Verified','Waived')",[sid]);if(Number(gt[0].c)!==1)throw new Error('Payment gate failed');ok('payment_gate','verified publication fee and evidence satisfy gate');
 await c.execute('INSERT INTO submission_authors(submission_id,sort_order,name,affiliation,orcid,scopus_id) VALUES(?,?,?,?,?,?),(?,?,?,?,?,?)',[sid,1,'Synthetic Author One','Synthetic University','0000-0000-0000-0001','1234567890',sid,2,'Synthetic Author Two','Synthetic Institute','0000-0000-0000-0002','0987654321']);const [ars]=await c.execute('SELECT name,affiliation,orcid,scopus_id FROM submission_authors WHERE submission_id=? ORDER BY sort_order,id',[sid]);if(ars.length!==2||ars[0].name!=='Synthetic Author One')throw new Error('Structured authors failed');ok('structured_authors','author order, affiliation, ORCID and Scopus ID verified');
 await c.execute("UPDATE production_items SET production_status='Published',issue_label=?,pages='1-12',doi='10.0000/synthetic-na-audit',published_at=NOW() WHERE submission_id=?",[il,sid]);await c.execute("UPDATE submissions SET stage='Publication',status='Published' WHERE id=?",[sid]);const [ar]=await c.execute("SELECT s.id,p.issue_label,p.pages,p.doi FROM submissions s JOIN production_items p ON p.submission_id=s.id WHERE s.id=? AND s.status='Published' AND p.published_at IS NOT NULL",[sid]);if(ar.length!==1||ar[0].issue_label!==il||ar[0].pages!=='1-12')throw new Error('Article query failed');ok('public_article','published article query verified');
 const [cur]=await c.execute("SELECT i.id,CONCAT('Vol. ',i.volume,' No. ',i.number,' (',i.year,')') issue_label FROM issues i WHERE i.id=? AND i.status='Published' AND EXISTS(SELECT 1 FROM production_items p JOIN submissions s ON s.id=p.submission_id WHERE s.status='Published' AND p.issue_label=CONCAT('Vol. ',i.volume,' No. ',i.number,' (',i.year,')'))",[iid]);if(cur.length!==1||cur[0].issue_label!==il)throw new Error('Current issue grouping failed');const [arc]=await c.execute("SELECT p.issue_label,COUNT(*) articles FROM production_items p JOIN submissions s ON s.id=p.submission_id WHERE s.status='Published' AND p.issue_label=? GROUP BY p.issue_label",[il]);if(arc.length!==1||Number(arc[0].articles)!==1)throw new Error('Archive grouping failed');ok('issue_grouping','current issue and archives grouping verified');
 await c.rollback();c.release();c=null;ok('rollback','synthetic transaction rolled back');
 v=await pool.getConnection();for(const [table,where,param] of [['users','email LIKE ?',('%'+P.toLowerCase()+'%')],['submissions','title LIKE ?',('%'+P+'%')],['issues','title LIKE ?',('%'+P+'%')],['apc_payments','reference_no LIKE ?',('%'+P+'%')],['payment_evidence','original_name LIKE ?',('%'+P+'%')]]){const [rows]=await v.execute('SELECT COUNT(*) c FROM '+table+' WHERE '+where,[param]);if(Number(rows[0].c)!==0)throw new Error('Rollback cleanup failed for '+table)}ok('cleanup','zero synthetic rows remain');
 console.log('\n=== SYNTHETIC AUDIT SUMMARY ===');for(const s of pass)console.log(s+': PASS');console.log('TOTAL='+pass.length+' PASS='+pass.length+' FAIL=0');process.exit(0);
}catch(err){console.error('[FAIL]',err?.stack||err?.message||String(err));if(c){try{await c.rollback()}catch{}try{c.release()}catch{}}process.exit(1)}finally{if(v)try{v.release()}catch{}await pool.end()}
